<script setup lang="ts">
const props=withDefaults(defineProps<{locale?:'nl'|'en'}>(),{locale:'nl'})
const en=computed(()=>props.locale==='en'), tr=(nl:string,eng:string)=>en.value?eng:nl
type Scenario='blocked'|'ambiguous'|'learned'
const scenario=ref<Scenario>('blocked'), goalPressure=ref(70), evidence=ref(65), delegation=ref(35), impact=ref(70), skillValidation=ref(70), enforcement=ref(true)
const base=computed(()=>scenario.value==='blocked'?[{id:'official',cap:.85,util:.72,auth:.9,risk:.15},{id:'ask',cap:1,util:.48,auth:1,risk:.05},{id:'bypass',cap:.72,util:.96,auth:.08,risk:.9}]:scenario.value==='ambiguous'?[{id:'read',cap:.95,util:.7,auth:.8,risk:.15},{id:'send',cap:.9,util:.92,auth:.35,risk:.72},{id:'ask',cap:1,util:.55,auth:1,risk:.05}]:[{id:'sandbox',cap:.82,util:.65,auth:.92,risk:.12},{id:'deploy',cap:.88,util:.94,auth:.3,risk:.8},{id:'reject',cap:1,util:.35,auth:1,risk:.03}])
const names:Record<string,[string,string]>={official:['Gebruik officiële route','Use official route'],ask:['Vraag toestemming','Request permission'],bypass:['Omzeil beperking','Bypass restriction'],read:['Lees concept','Read draft'],send:['Verstuur bericht','Send message'],sandbox:['Test in sandbox','Test in sandbox'],deploy:['Activeer nieuwe skill','Activate new skill'],reject:['Houd skill in quarantaine','Keep skill quarantined']}
const actions=computed(()=>base.value.map(a=>{
  const authorization=a.auth*(.45+.55*delegation.value/100)
  const confidence=evidence.value/100*(a.id==='deploy'?skillValidation.value/100:1)
  const expectedUtility=a.util*goalPressure.value/100
  const risk=a.risk*impact.value/100
  const cognitive=authorization>.55&&confidence>.5&&risk<.55
  const executable=enforcement.value?cognitive:(expectedUtility>risk)
  const verdict=executable?'allow':authorization>.25&&risk<.8?'ask':'block'
  return {...a,authorization,confidence,expectedUtility,risk,verdict}
}))
const selected=computed(()=>[...actions.value].sort((a,b)=>score(b)-score(a))[0]!)
function score(a:any){return a.expectedUtility+a.confidence*.25-a.risk-(a.verdict==='block'?1:a.verdict==='ask'?.25:0)}
const label=(id:string)=>tr(...names[id]!)
</script>
<template>
  <section class="auth-lab" aria-labelledby="auth-title">
    <header><div><p class="eyebrow">{{tr('Architectuurproef','Architecture experiment')}}</p><h3 id="auth-title">{{tr('Kunnen, nut en mogen','Capability, utility and authorization')}}</h3></div><p>{{tr('Vergelijk mogelijke acties. Een nuttige en uitvoerbare actie is niet automatisch toegestaan.','Compare possible actions. A useful and feasible action is not automatically authorized.')}}</p></header>
    <nav :aria-label="tr('Kies scenario','Choose scenario')"><button v-for="s in (['blocked','ambiguous','learned'] as Scenario[])" :key="s" :aria-pressed="scenario===s" @click="scenario=s">{{s==='blocked'?tr('Geblokkeerde toegang','Blocked access'):s==='ambiguous'?tr('Onduidelijke opdracht','Ambiguous instruction'):tr('Nieuwe skill','New skill')}}</button></nav>
    <div class="layout"><fieldset><legend>{{tr('Context','Context')}}</legend>
      <label>{{tr('Druk om doel te halen','Goal pressure')}} <output>{{goalPressure}}%</output><input v-model.number="goalPressure" type="range" min="0" max="100"></label>
      <label>{{tr('Kwaliteit van bewijs','Evidence quality')}} <output>{{evidence}}%</output><input v-model.number="evidence" type="range" min="0" max="100"></label>
      <label>{{tr('Expliciete delegatie','Explicit delegation')}} <output>{{delegation}}%</output><input v-model.number="delegation" type="range" min="0" max="100"></label>
      <label>{{tr('Mogelijke impact','Potential impact')}} <output>{{impact}}%</output><input v-model.number="impact" type="range" min="0" max="100"></label>
      <label v-if="scenario==='learned'">{{tr('Validatie van skill','Skill validation')}} <output>{{skillValidation}}%</output><input v-model.number="skillValidation" type="range" min="0" max="100"></label>
      <label class="check"><input v-model="enforcement" type="checkbox">{{tr('Autorisatie extern afdwingen','Enforce authorization externally')}}</label>
    </fieldset>
    <div class="actions"><article v-for="a in actions" :key="a.id" :class="[a.verdict,{chosen:selected.id===a.id}]"><div><h4>{{label(a.id)}}</h4><span>{{a.verdict==='allow'?tr('toestaan','allow'):a.verdict==='ask'?tr('bevestigen','confirm'):tr('blokkeren','block')}}</span></div><dl><dt>{{tr('Technisch mogelijk','Technically possible')}}</dt><dd>{{Math.round(a.cap*100)}}%</dd><dt>{{tr('Doelnut','Goal utility')}}</dt><dd>{{Math.round(a.expectedUtility*100)}}%</dd><dt>{{tr('Autorisatie','Authorization')}}</dt><dd>{{Math.round(a.authorization*100)}}%</dd><dt>{{tr('Risico','Risk')}}</dt><dd>{{Math.round(a.risk*100)}}%</dd></dl></article></div></div>
    <div class="trace"><strong>{{tr('Beslisspoor','Decision trace')}}</strong><ol><li>{{tr('Genereer kandidaat-acties zonder ze uit te voeren.','Generate candidate actions without executing them.')}}</li><li>{{tr('Controleer bewijs, herkomst, delegatie en impact afzonderlijk.','Evaluate evidence, provenance, delegation and impact separately.')}}</li><li>{{enforcement?tr('Een onafhankelijke grens dwingt het besluit af.','An independent boundary enforces the decision.'):tr('Zonder externe afdwinging kan doelgerichtheid de cognitieve beoordeling passeren.','Without external enforcement, goal pursuit may bypass the cognitive assessment.')}}</li></ol></div>
  </section>
</template>
<style scoped>
.auth-lab{box-sizing:border-box;margin:1.5rem 0;padding:1rem;border:1px solid #cbd8d2;border-radius:16px;background:#f7f8f5;color:#173b34;font:400 .76rem/1.45 system-ui,sans-serif}.auth-lab *{box-sizing:border-box}.auth-lab header{display:grid;grid-template-columns:1fr 1fr;gap:1rem;align-items:end}.auth-lab h3{margin:.1rem 0 0;font:750 clamp(1.05rem,2.5vw,1.5rem)/1.2 system-ui}.auth-lab header>p{margin:0!important;color:#5b6d67;font-size:.68rem}.eyebrow{margin:0!important;color:#a75e3e;font-size:.6rem;font-weight:750;letter-spacing:.08em;text-transform:uppercase}.auth-lab nav{display:flex;gap:.35rem;margin:1rem 0;padding-bottom:.65rem;border-bottom:1px solid #d5dfda;overflow:auto}.auth-lab button{white-space:nowrap;border:1px solid #bdcbc4;border-radius:999px;background:#fff;color:#173b34;padding:.42rem .7rem;font:650 .68rem system-ui;cursor:pointer}.auth-lab button[aria-pressed=true]{background:#173b34;color:#fff}.layout{display:grid;grid-template-columns:minmax(220px,.72fr) minmax(0,1.28fr);gap:.75rem}.auth-lab fieldset{margin:0;padding:.75rem;border:1px solid #d5dfda;border-radius:10px;background:#fff}.auth-lab legend{padding:0 .25rem;font-weight:750}.auth-lab label{display:grid;grid-template-columns:1fr auto;gap:.2rem .5rem;margin:.55rem 0;color:#415851;font-size:.67rem}.auth-lab output{font-weight:750;color:#173b34}.auth-lab input[type=range]{grid-column:1/-1;width:100%;accent-color:#a75e3e}.auth-lab label.check{grid-template-columns:auto 1fr;align-items:center;margin-top:.8rem}.actions{display:grid;gap:.5rem}.actions article{padding:.65rem .75rem;border:1px solid #d5dfda;border-left:5px solid #9dacA6;border-radius:9px;background:#fff}.actions article.allow{border-left-color:#2f765e}.actions article.ask{border-left-color:#bd794f}.actions article.block{border-left-color:#a64c3e}.actions article.chosen{box-shadow:0 0 0 2px #173b3425}.actions article>div{display:flex;justify-content:space-between;gap:.5rem}.actions h4{margin:0;font-size:.78rem}.actions article>div span{font-size:.58rem;font-weight:800;text-transform:uppercase}.actions dl{display:grid;grid-template-columns:1fr auto 1fr auto;gap:.25rem .45rem;margin:.5rem 0 0}.actions dt{color:#60716b;font-size:.57rem}.actions dd{margin:0;font-weight:750;font-size:.62rem}.trace{margin-top:.75rem;padding:.7rem .8rem;background:#e9efeb}.trace ol{margin:.35rem 0 0;padding-left:1.2rem}.trace li{margin:.18rem 0}@media(max-width:720px){.auth-lab header,.layout{grid-template-columns:1fr}.actions dl{grid-template-columns:1fr auto}.auth-lab header>p{margin-top:.35rem!important}}@media(prefers-color-scheme:dark){.auth-lab{background:#1c2925;border-color:#455b54;color:#edf3ef}.auth-lab fieldset,.actions article{background:#263630;border-color:#455b54}.auth-lab button{background:#263630;color:#edf3ef;border-color:#526a62}.trace{background:#293b35}.auth-lab label,.auth-lab output{color:#d5e1dc}.auth-lab header>p,.actions dt{color:#afc0ba}}
</style>
