<script setup lang="ts">
import { activationAt, consciousnessPrediction } from '~/utils/consciousnessSimulation'
const props=withDefaults(defineProps<{locale?:'nl'|'en'}>(),{locale:'nl'}); const nl=computed(()=>props.locale==='nl')
const p=reactive({conflict:.72,novelty:.62,integration:.68,relevance:.8,urgency:.35,learnedAutomaticity:.18,arousal:.62})
const time=ref(480); const r=computed(()=>consciousnessPrediction(p)); const activation=computed(()=>activationAt(time.value,r.value.consciousAccess))
const controls=computed(()=>[
  ['conflict',nl.value?'Conflict':'Conflict'],['novelty',nl.value?'Nieuwheid':'Novelty'],['integration',nl.value?'Integratiebehoefte':'Integration demand'],['relevance',nl.value?'Relevantie voor doelen/welzijn':'Goal/welfare relevance'],['urgency',nl.value?'Urgentie':'Urgency'],['learnedAutomaticity',nl.value?'Aangeleerde automatisering':'Learned automaticity'],['arousal',nl.value?'Beschikbare activatie':'Available arousal']
] as const)
const pct=(v:number)=>`${Math.round(v*100)}%`; const x=(v:number)=>40+v*520
const curve=computed(()=>Array.from({length:51},(_,i)=>{const t=i*20;const y=160-activationAt(t,r.value.consciousAccess)*120;return `${i?'L':'M'}${40+t/1000*520} ${y}`}).join(' '))
const preset=(name:'routine'|'conflict'|'urgent')=>Object.assign(p,name==='routine'?{conflict:.08,novelty:.05,integration:.15,relevance:.45,urgency:.1,learnedAutomaticity:.92,arousal:.55}:name==='conflict'?{conflict:.9,novelty:.7,integration:.85,relevance:.8,urgency:.35,learnedAutomaticity:.1,arousal:.65}:{conflict:.45,novelty:.5,integration:.5,relevance:.95,urgency:.95,learnedAutomaticity:.2,arousal:.8})
</script>
<template>
 <section class="consciousness-model" data-analytics-model="consciousness-hypothesis">
  <header><p class="eyebrow">{{nl?'INTERACTIEVE HYPOTHESE':'INTERACTIVE HYPOTHESIS'}}</p><h3>{{nl?'Wanneer voorspelt het model bewuste toegang?':'When does the model predict conscious access?'}}</h3><p>{{nl?'Stel een taaktoestand samen. Het model combineert arbitragebehoefte, relevantie en beschikbaarheid; automatisering onderdrukt de voorspelde behoefte aan bewuste toegang.':'Compose a task state. The model combines arbitration demand, relevance and availability; automaticity suppresses the predicted need for conscious access.'}}</p></header>
  <div class="presets"><button @click="preset('routine')">{{nl?'Routine':'Routine'}}</button><button @click="preset('conflict')">{{nl?'Nieuw conflict':'Novel conflict'}}</button><button @click="preset('urgent')">{{nl?'Urgent en relevant':'Urgent and relevant'}}</button></div>
  <div class="model-grid">
   <div class="controls"><label v-for="([key,name]) in controls" :key="key"><span>{{name}} <b>{{pct(p[key])}}</b></span><input v-model.number="p[key]" type="range" min="0" max="1" step=".01"></label></div>
   <div class="result-panel">
    <div class="scores"><article><small>{{nl?'ARBITRAGEBEHOEFTE':'ARBITRATION DEMAND'}}</small><strong>{{pct(r.arbitrationNeed)}}</strong></article><article><small>{{nl?'VOORSPELDE BEWUSTE TOEGANG':'PREDICTED CONSCIOUS ACCESS'}}</small><strong>{{pct(r.consciousAccess)}}</strong></article><article><small>{{nl?'VOORSPELDE RAPPORTAGE':'PREDICTED REPORTABILITY'}}</small><strong>{{pct(r.reportability)}}</strong></article></div>
    <svg viewBox="0 0 600 190" role="img" :aria-label="nl?'Voorspelde activatie over één seconde':'Predicted activation over one second'"><path d="M40 160H560M40 30V160" class="axis"/><path :d="curve" class="curve"/><line :x1="x(time/1000)" y1="25" :x2="x(time/1000)" y2="165" class="now"/><text x="40" y="180">0 ms</text><text x="560" y="180" text-anchor="end">1000 ms</text></svg>
    <label class="time"><span>{{nl?'Moment in verwerking':'Processing time'}} <b>{{time}} ms</b></span><input v-model.number="time" type="range" min="0" max="1000" step="10"></label>
    <p class="activation">{{nl?'Activering op dit moment':'Activation at this moment'}}: <strong>{{pct(activation)}}</strong> · {{nl?'geschatte reactietijd':'estimated reaction time'}}: <strong>{{Math.round(r.reactionDelayMs)}} ms</strong></p>
   </div>
  </div>
  <p class="note">{{nl?'Dit is een operationalisering van de hypothese uit het artikel, geen gevalideerde bewustzijnsmeter. De gewichten en drempels zijn expliciete, aanpasbare modelaannames; een echt experiment moet ze schatten of weerleggen.':'This operationalises the article’s hypothesis; it is not a validated consciousness meter. Weights and thresholds are explicit, revisable model assumptions that an actual experiment would need to estimate or falsify.'}}</p>
 </section>
</template>
<style scoped>
.consciousness-model{margin:4rem calc((780px - min(1120px,calc(100vw - 48px)))/2);width:min(1120px,calc(100vw - 48px));background:#f7f6f1;border:1px solid #d9dedc;border-radius:20px;padding:clamp(1rem,3vw,2rem);color:#172321}.consciousness-model header{max-width:780px}.eyebrow{font-size:.74rem;letter-spacing:.12em;font-weight:800;color:#b44f38;margin:0}.consciousness-model h3{font-size:clamp(1.7rem,3vw,2.5rem);margin:.25rem 0 .7rem}.presets{display:flex;gap:.5rem;flex-wrap:wrap;margin:1.25rem 0}.presets button{border:1px solid #ccd4d0;background:white;border-radius:999px;padding:.55rem .85rem;cursor:pointer}.model-grid{display:grid;grid-template-columns:minmax(260px,.8fr) minmax(420px,1.2fr);gap:1rem}.controls,.result-panel{background:white;border:1px solid #dce2de;border-radius:14px;padding:1rem}.controls{display:grid;gap:.78rem}.controls label span,.time span{display:flex;justify-content:space-between;gap:1rem;font-size:.86rem}.controls input,.time input{width:100%;accent-color:#b44f38}.scores{display:grid;grid-template-columns:repeat(3,1fr);gap:.5rem}.scores article{background:#f3f5f2;border-radius:9px;padding:.75rem}.scores small{display:block;font-size:.62rem;letter-spacing:.06em;color:#65716d;min-height:2.4em}.scores strong{font-size:1.3rem}.result-panel svg{width:100%;display:block;margin:.65rem 0}.axis{fill:none;stroke:#aab5b0;stroke-width:2}.curve{fill:none;stroke:#b44f38;stroke-width:5}.now{stroke:#1e5960;stroke-width:2;stroke-dasharray:5}.result-panel svg text{font:12px system-ui;fill:#66726e}.activation{font-size:.86rem}.note{font-size:.79rem;color:#66726e;margin-bottom:0}@media(max-width:760px){.consciousness-model{margin:3rem calc(50% - 50vw + 16px);width:calc(100vw - 32px)}.model-grid{grid-template-columns:1fr}.scores{grid-template-columns:1fr}.scores small{min-height:0}}
</style>
