<script setup lang="ts">
import { causalPaths, defaults, presets, register, sectorDefinitions, simulate, type MigrationView, type ModelParams } from '~/utils/migrationLabourSystem'
const props=withDefaults(defineProps<{view?:MigrationView;locale?:'nl'|'en'}>(),{view:'full',locale:'nl'})
const nl=computed(()=>props.locale==='nl')
const p=reactive<ModelParams>({...defaults,sectorScales:{...defaults.sectorScales},sectorProductivity:{...defaults.sectorProductivity},publicAllocation:{...defaults.publicAllocation}})
const scenario=ref('baseline'), why=ref('shortage'), showRegister=ref(false)
const showSectors=ref(true), showPublic=ref(true), selectedSectors=ref<string[]>(sectorDefinitions.map(s=>s.id))
const showCore=ref(true),showBalances=ref(true),showSectorCharts=ref(true),showWhy=ref(true),activeSector=ref('livestock')
const showLand=ref(true)
const rows=computed(()=>simulate(p)); const last=computed(()=>rows.value.at(-1)!)
const baselineRows=computed(()=>simulate(defaults)); const baselineLast=computed(()=>baselineRows.value.at(-1)!)
const setScenario=()=>Object.assign(p,{...defaults,sectorScales:{...defaults.sectorScales},sectorProductivity:{...defaults.sectorProductivity},publicAllocation:{...defaults.publicAllocation}},presets[scenario.value]||{})
const fmt=(n:number,d=0)=>new Intl.NumberFormat(nl.value?'nl-NL':'en-GB',{maximumFractionDigits:d}).format(n)
const millions=(n:number)=>`${fmt(n/1e6,2)} ${nl.value?'mln':'m'}`
const labels=computed(()=>nl.value?{
 title:'Systeemverkenner',sub:'Eén jaarlijkse rekenkern, hier bekeken vanuit een ander deel van het systeem.',migration:'Netto migratie per jaar',participation:'Arbeidsparticipatie',hours:'Gemiddelde uren per week',productivity:'Productiviteitsgroei per jaar',sector:'Groei economische vraag',care:'Extra groei zorgvraag',homes:'Nieuwe woningen per jaar',grid:'Groei netcapaciteit',unpaid:'Verdringing onbetaald werk',livestock:'Omvang veehouderij',crop:'Omvang akker- en tuinbouw',automation:'Technologische investering',mode:'Migratie-instelling',manual:'Handmatig',responsive:'Reageert deels op krapte',response:'Aandeel krapte-respons via migratie',population:'Bevolking',supply:'Effectief arbeidsaanbod',demand:'Arbeidsvraag',shortage:'Arbeidstekort',older:'67-plus',housing:'Woningbalans (+ tekort / − overschot)',careDemand:'Zorgvraag-index',gdp:'Productie-index',gridGap:'Netvraag / capaciteit',why:'Waarom verandert dit?',registry:'Bronnen en aannames bekijken',obs:'Soort',source:'Herkomst / status'
}:{
 title:'System explorer',sub:'One annual calculation engine, viewed through a different part of the system.',migration:'Annual net migration',participation:'Labour-force participation',hours:'Average weekly hours',productivity:'Annual productivity growth',sector:'Growth in economic demand',care:'Additional care-demand growth',homes:'New homes per year',grid:'Grid-capacity growth',unpaid:'Displacement of unpaid work',livestock:'Livestock sector scale',crop:'Crop and horticulture scale',automation:'Technology investment',mode:'Migration setting',manual:'Manual',responsive:'Partly responds to shortages',response:'Share of shortage response through migration',population:'Population',supply:'Effective labour supply',demand:'Labour demand',shortage:'Labour shortage',older:'Aged 67+',housing:'Housing balance (+ shortage / − surplus)',careDemand:'Care-demand index',gdp:'Output index',gridGap:'Grid demand / capacity',why:'Why does this change?',registry:'View sources and assumptions',obs:'Type',source:'Origin / status'})
const controls=computed(()=>({
 migration:['netMigration','participation'],demography:['netMigration','careGrowth'],labour:['participation','weeklyHours','unpaidDisplacement'],sectors:['sectorGrowth','productivityGrowth','automation'],agriculture:['livestockTarget','cropTarget','automation'],resources:['housingBuild','gridGrowth','livestockTarget'],feedback:['migrationMode','netMigration','migrationResponse','automation'],full:['netMigration','participation','weeklyHours','productivityGrowth','sectorGrowth','housingBuild','gridGrowth','migrationMode','migrationResponse']
}[props.view]))
const defs:any={
 netMigration:['migration',-30000,180000,5000],participation:['participation',60,82,.5],weeklyHours:['hours',24,38,.5],productivityGrowth:['productivity',0,3,.1],sectorGrowth:['sector',-.5,3,.1],careGrowth:['care',0,2.5,.1],housingBuild:['homes',30000,150000,5000],gridGrowth:['grid',0,4,.1],unpaidDisplacement:['unpaid',0,60,2],livestockTarget:['livestock',30,130,5],cropTarget:['crop',60,140,5],automation:['automation',0,3,.1],migrationResponse:['response',0,45,1]
}
type ResultKey='labourSupply'|'labourDemand'|'population'|'workingAge'|'older'|'housingGap'|'careDemand'|'gridDemand'|'realisedGridDemand'|'gridCapacity'|'territorialEmissions'|'consumptionFootprint'|'landDemand'
const chartDomain=computed<[number,number]>(()=>{
 if(props.view==='demography') return [0,1.65]
 if(props.view==='resources') return [.5,2]
 if(props.view==='agriculture') return [.25,1.75]
 return [5e6,15e6]
})
function points(key:ResultKey,indexed=false,domain?:[number,number]){
 const raw=rows.value.map(r=>r[key]); const first=raw[0]||1
 const values=indexed?raw.map(v=>v/first):raw; const [min,max]=domain||chartDomain.value; const span=max-min
 return values.map((v,i)=>`${20+i*560/(values.length-1)},${170-(Math.max(min,Math.min(max,v))-min)*135/span}`).join(' ')
}
const metricCards=computed(()=>{
 const r=last.value,f=rows.value[0]; const c=(label:string,value:string,start:number,end:number)=>[label,value,direction(start,end)]
 const d=(label:string,value:string,start:number,end:number,difference:string)=>[label,value,direction(start,end),difference]
 if(props.view==='demography') return [c(labels.value.population,millions(r.population),f.population,r.population),c(nl.value?'Werkzame leeftijd':'Working age',millions(r.workingAge),f.workingAge,r.workingAge),c(labels.value.older,millions(r.older),f.older,r.older),c(labels.value.careDemand,fmt(r.careDemand,2),f.careDemand,r.careDemand)]
 if(props.view==='labour') return [c(labels.value.supply,millions(r.labourSupply),f.labourSupply,r.labourSupply),c(labels.value.demand,millions(r.labourDemand),f.labourDemand,r.labourDemand),c(nl.value?'Arbeidsbalans (+ tekort / − overschot)':'Labour balance (+ shortage / − surplus)',`${signed(r.shortage/1e6,2)} ${nl.value?'mln':'m'}`,f.shortage,r.shortage),[nl.value?'Verdringing onbetaald werk':'Displacement of unpaid work',`${fmt(p.unpaidDisplacement)}%`,'flat']]
 if(props.view==='resources') return [c(labels.value.population,millions(r.population),f.population,r.population),c(labels.value.housing,`${signed(r.housingGap/1000)} × 1.000`,f.housingGap,r.housingGap),c(nl.value?'Gevraagde netcapaciteit':'Requested grid capacity',fmt(r.gridDemand),f.gridDemand,r.gridDemand),c(nl.value?'Gerealiseerd netgebruik':'Realised grid use',fmt(r.realisedGridDemand),f.realisedGridDemand,r.realisedGridDemand)]
 if(props.view==='agriculture') return [c(nl.value?'Territoriale uitstoot':'Territorial emissions',fmt(r.territorialEmissions),f.territorialEmissions,r.territorialEmissions),c(nl.value?'Consumptievoetafdruk':'Consumption footprint',fmt(r.consumptionFootprint),f.consumptionFootprint,r.consumptionFootprint),c(nl.value?'Grondgebruik-index':'Land-use index',fmt(r.landDemand,1),f.landDemand,r.landDemand),c(nl.value?'Milieudruk-index':'Environmental-pressure index',fmt(r.ecologyPressure),f.ecologyPressure,r.ecologyPressure)]
 if(props.view==='full') {const b=baselineLast.value;return [d(labels.value.population,millions(r.population),f.population,r.population,`${signed((r.population-b.population)/1e6,2)} ${nl.value?'mln':'m'}`),d(nl.value?'Arbeidsbalans (+ tekort)':'Labour balance (+ shortage)',`${signed(r.shortage/1e6,2)} ${nl.value?'mln':'m'}`,f.shortage,r.shortage,`${signed((r.shortage-b.shortage)/1e6,2)} ${nl.value?'mln':'m'}`),d(labels.value.housing,`${signed(r.housingGap/1000)} × 1.000`,f.housingGap,r.housingGap,`${signed((r.housingGap-b.housingGap)/1000)} × 1.000`),d(nl.value?'Marge elektriciteitsnet':'Electricity-grid margin',signed(r.gridCapacity-r.gridDemand,1),f.gridCapacity-f.gridDemand,r.gridCapacity-r.gridDemand,signed((r.gridCapacity-r.gridDemand)-(b.gridCapacity-b.gridDemand),1)),d(labels.value.careDemand,fmt(r.careDemand,2),f.careDemand,r.careDemand,signed(r.careDemand-b.careDemand,2)),d(nl.value?'Milieudruk-index':'Environmental-pressure index',fmt(r.ecologyPressure),f.ecologyPressure,r.ecologyPressure,signed(r.ecologyPressure-b.ecologyPressure,1)),d(nl.value?'Publiek fiscaal saldo-index':'Public fiscal-balance index',signed(r.fiscalBalance,1),f.fiscalBalance,r.fiscalBalance,signed(r.fiscalBalance-b.fiscalBalance,1)),d(nl.value?'Productie per inwoner-index':'Output-per-capita index',fmt(r.gdpPerCapita),f.gdpPerCapita,r.gdpPerCapita,signed(r.gdpPerCapita-b.gdpPerCapita,1))]}
 return [c(labels.value.population,millions(r.population),f.population,r.population),c(labels.value.shortage,`${signed(r.shortage/1e6,2)} ${nl.value?'mln':'m'}`,f.shortage,r.shortage),c(labels.value.older,millions(r.older),f.older,r.older),c(labels.value.gdp,fmt(r.gdp),f.gdp,r.gdp)]
})
const palette=['#28685e','#bf7138','#70528d','#3f78a1','#9a4d54','#71813b','#bb9840','#54706e','#845f45','#487f86','#8a7565']
const sectorName=(id:string)=>{const s=sectorDefinitions.find(x=>x.id===id);return s?(nl.value?s.nl:s.en):id}
const sectorColor=(id:string)=>palette[Math.max(0,sectorDefinitions.findIndex(s=>s.id===id))%palette.length]
const sectorTotalMax=computed(()=>Math.max(...rows.value.map(r=>Object.values(r.sectors).reduce((a,s)=>a+s.labourDemand,0)))*1.04)
function sectorAreaPath(id:string){
 const index=sectorDefinitions.findIndex(s=>s.id===id), n=rows.value.length, upper:string[]=[], lower:string[]=[]
 rows.value.forEach((r,i)=>{const before=sectorDefinitions.slice(0,index).reduce((a,s)=>a+r.sectors[s.id].labourDemand,0);const value=r.sectors[id].labourDemand;const x=20+i*560/(n-1);upper.push(`${x},${170-(before+value)/sectorTotalMax.value*135}`);lower.unshift(`${x},${170-before/sectorTotalMax.value*135}`)})
 return `M${upper.join(' L')} L${lower.join(' L')} Z`
}
function sectorLinePoints(id:string,potential=false){
 const values=rows.value.map(r=>potential?r.sectors[id].potentialOutput:r.sectors[id].output); return values.map((v,i)=>`${20+i*560/(values.length-1)},${170-(Math.max(60,Math.min(180,v))-60)*135/120}`).join(' ')
}
function toggleSector(id:string){
 const found=selectedSectors.value.indexOf(id)
 if(found>=0) selectedSectors.value.splice(found,1)
 else selectedSectors.value.push(id)
}
type FiscalKey='publicRevenue'|'publicCosts'|'publicInvestment'|'fiscalBalance'
const fiscalDomain=computed(()=>{const values=rows.value.flatMap(r=>[r.publicRevenue,r.publicCosts,r.publicInvestment,r.fiscalBalance]);return [Math.min(0,...values)*1.1,Math.max(...values)*1.1] as [number,number]})
function fiscalPoints(key:FiscalKey){const [min,max]=fiscalDomain.value,span=max-min||1;return rows.value.map((r,i)=>`${20+i*560/(rows.value.length-1)},${170-(r[key]-min)*135/span}`).join(' ')}
const allocationTotal=computed(()=>Object.values(p.publicAllocation).reduce((a,b)=>a+b,0)||1)
const allocationPct=(key:string)=>fmt((p.publicAllocation[key]||0)/allocationTotal.value*100)
const constraintLabel=(key:string)=>({permit:nl.value?'vergunningruimte':'permit capacity',land:nl.value?'geschikte bouwgrond':'suitable building land',infrastructure:nl.value?'water, net en infrastructuur':'water, grid and infrastructure',labour:nl.value?'bouwcapaciteit en arbeid':'construction capacity and labour',ambition:nl.value?'ingestelde bouwambitie':'selected building ambition'}[key]||key)
const resourceLabel=(key:string)=>({none:nl.value?'geen resourcebeperking':'no resource constraint',labour:nl.value?'arbeid':'labour',grid:nl.value?'elektriciteitsnet':'electricity grid',land:nl.value?'grond':'land',ecology:nl.value?'ecologische ruimte':'ecological capacity',infrastructure:nl.value?'infrastructuur':'infrastructure'}[key]||key)
const resourceCards=computed(()=>Object.entries(last.value.resourceAvailability).map(([id,value])=>({id,label:resourceLabel(id),value:value*100,limited:value<.995})))
const direction=(start:number,end:number)=>Math.abs(end-start)<Math.max(1,Math.abs(start)*.002)?'flat':end>start?'up':'down'
const directionLabel=(dir:string)=>nl.value?(dir==='up'?'stijgend':dir==='down'?'dalend':'vrijwel gelijk'):(dir==='up'?'rising':dir==='down'?'falling':'roughly stable')
const signed=(n:number,d=0)=>`${n>0?'+':''}${fmt(n,d)}`
const first=computed(()=>rows.value[0])
const systemSeries=computed(()=>[
 {id:'labour',label:nl.value?'Arbeidsbalans (mln; + tekort)':'Labour balance (m; + shortage)',values:rows.value.map(r=>r.shortage/1e6)},
 {id:'housing',label:nl.value?'Woningbalans (× 1.000; + tekort)':'Housing balance (× 1,000; + shortage)',values:rows.value.map(r=>r.housingGap/1000)},
 {id:'grid',label:nl.value?'Marge netcapaciteit na gevraagde belasting':'Grid-capacity margin after requested load',values:rows.value.map(r=>r.gridCapacity-r.gridDemand)},
 {id:'care',label:nl.value?'Zorgvraag-index':'Care-demand index',values:rows.value.map(r=>r.careDemand)},
 {id:'ecology',label:nl.value?'Milieudruk-index':'Environmental-pressure index',values:rows.value.map(r=>r.ecologyPressure)},
 {id:'fiscal',label:nl.value?'Publiek fiscaal saldo-index':'Public fiscal-balance index',values:rows.value.map(r=>r.fiscalBalance)}
])
const loadSeriesFor=(data:ReturnType<typeof simulate>,infrastructureReadiness:number)=>[
 {id:'load-labour',label:nl.value?'Arbeid':'Labour',values:data.map(r=>r.labourDemand/Math.max(1,r.labourSupply)*100),color:'#2e7165'},
 {id:'load-grid',label:nl.value?'Elektriciteitsnet':'Electricity grid',values:data.map(r=>r.gridDemand/Math.max(1,r.gridCapacity)*100),color:'#c07b3c'},
 {id:'load-land',label:nl.value?'Grond':'Land',values:data.map(r=>r.landDemand/43.2*100),color:'#745895'},
 {id:'load-ecology',label:nl.value?'Ecologische ruimte':'Ecological capacity',values:data.map(r=>r.ecologyPressure),color:'#a44d42'},
 {id:'load-infrastructure',label:nl.value?'Infrastructuur':'Infrastructure',values:data.map(()=>10000/Math.max(1,infrastructureReadiness)),color:'#3f78a1'}
]
const systemLoadSeries=computed(()=>loadSeriesFor(rows.value,p.infrastructureReadiness))
const baselineSystemLoadSeries=computed(()=>loadSeriesFor(baselineRows.value,defaults.infrastructureReadiness))
const scenarioDifferences=computed(()=>{
 const current=last.value,base=baselineLast.value
 return [
  {id:'population',label:labels.value.population,value:(current.population-base.population)/1000,unit:nl.value?' × 1.000':'k'},
  {id:'labour',label:nl.value?'Arbeidsbalans':'Labour balance',value:(current.shortage-base.shortage)/1000,unit:nl.value?' × 1.000':'k'},
  {id:'housing',label:nl.value?'Woningbalans':'Housing balance',value:(current.housingGap-base.housingGap)/1000,unit:nl.value?' × 1.000':'k'},
  {id:'output',label:nl.value?'Productie per inwoner':'Output per capita',value:current.gdpPerCapita-base.gdpPerCapita,unit:' index'},
  {id:'ecology',label:nl.value?'Milieudruk':'Environmental pressure',value:current.ecologyPressure-base.ecologyPressure,unit:' index'},
  {id:'fiscal',label:nl.value?'Publiek saldo':'Public balance',value:current.fiscalBalance-base.fiscalBalance,unit:' index'}
 ]
})
function systemLoadPoints(values:number[]){const lo=40,hi=170;return values.map((v,i)=>`${20+i*560/(values.length-1)},${170-(Math.max(lo,Math.min(hi,v))-lo)*135/(hi-lo)}`).join(' ')}
function sparkDomain(values:number[],includeZero=false){const rawMin=Math.min(...values),rawMax=Math.max(...values),min=includeZero?Math.min(0,rawMin):rawMin,max=includeZero?Math.max(0,rawMax):rawMax,pad=(max-min||1)*.08;return {lo:min-pad,span:max-min+2*pad}}
function sparkPoints(values:number[],includeZero=false){const {lo,span}=sparkDomain(values,includeZero);return values.map((v,i)=>`${8+i*184/(values.length-1)},${58-(v-lo)*48/span}`).join(' ')}
function sparkZeroY(values:number[]){const {lo,span}=sparkDomain(values,true);return 58-(0-lo)*48/span}
const activeSectorSeries=computed(()=>{
 const id=activeSector.value
 const reference=simulate({...p,sectorScales:{...p.sectorScales,[id]:100}})
 const series=(key:string,label:string,values:number[],referenceValues:number[])=>({id:key,label,values,referenceEnd:referenceValues.at(-1)??0})
 const common=[
  series('potential',nl.value?'Potentieel zonder resourcegrenzen':'Potential without resource limits',rows.value.map(r=>r.sectors[id].potentialOutput),reference.map(r=>r.sectors[id].potentialOutput)),
  series('output',nl.value?'Gerealiseerde productie-index':'Realised output index',rows.value.map(r=>r.sectors[id].output),reference.map(r=>r.sectors[id].output)),
  series('labour',nl.value?'Arbeidsvraag (mln)':'Labour demand (m)',rows.value.map(r=>r.sectors[id].labourDemand/1e6),reference.map(r=>r.sectors[id].labourDemand/1e6)),
  series('fiscal',nl.value?'Fiscaal saldo-index':'Fiscal-balance index',rows.value.map(r=>r.sectors[id].fiscalBalance),reference.map(r=>r.sectors[id].fiscalBalance))]
 if(id==='livestock'||id==='crops') return [common[0],common[1],series('ecology',nl.value?'Milieudruk-index (lager = minder druk)':'Environmental-pressure index (lower = less pressure)',rows.value.map(r=>r.ecologyPressure),reference.map(r=>r.ecologyPressure)),series('permits',nl.value?'Vergunningscapaciteit bouw (× 1.000)':'Building permit capacity (× 1,000)',rows.value.map(r=>r.permitCapacity/1000),reference.map(r=>r.permitCapacity/1000)),series('landcapacity',nl.value?'Potentiële bouwgrondcapaciteit (× 1.000)':'Potential building-land capacity (× 1,000)',rows.value.map(r=>r.housingLandCapacity/1000),reference.map(r=>r.housingLandCapacity/1000)),series('headroom',nl.value?'Marge bouwcapaciteit t.o.v. ambitie (+ ruimte / − tekort)':'Building-capacity margin vs ambition (+ room / − shortfall)',rows.value.map(r=>(r.availableHousebuildingCapacity-r.desiredHousebuilding)/1000),reference.map(r=>(r.availableHousebuildingCapacity-r.desiredHousebuilding)/1000))]
 const related=id==='construction'?series('housing',nl.value?'Woningbalans (× 1.000; + tekort)':'Housing balance (× 1,000; + shortage)',rows.value.map(r=>r.housingGap/1000),reference.map(r=>r.housingGap/1000)):id==='care'?series('care',nl.value?'Zorgvraag-index':'Care-demand index',rows.value.map(r=>r.careDemand),reference.map(r=>r.careDemand)):series('total',nl.value?'Totale arbeidsbalans (mln; + tekort)':'Total labour balance (m; + shortage)',rows.value.map(r=>r.shortage/1e6),reference.map(r=>r.shortage/1e6))
 return [...common,related]
})
</script>

<template>
 <section class="explorer" :class="`view-${view}`">
  <header><div><p class="eyebrow">{{ view==='full'?(nl?'VOLLEDIG SYSTEEM':'FULL SYSTEM'):(nl?'VENSTER OP HET MODEL':'MODEL VIEW') }}</p><h3>{{labels.title}}</h3><p>{{labels.sub}}</p></div>
   <label v-if="view==='full'" class="scenario"><span>{{nl?'Scenario':'Scenario'}}</span><select v-model="scenario" @change="setScenario"><option value="baseline">{{nl?'Basispad':'Baseline'}}</option><option value="lowerPopulation">{{nl?'Lagere bevolkingsgroei':'Lower population growth'}}</option><option value="higherPopulation">{{nl?'Hogere bevolkingsgroei':'Higher population growth'}}</option><option value="productivity">{{nl?'Hogere productiviteit':'Higher productivity'}}</option><option value="moreHours">{{nl?'Meer arbeidsuren':'More working hours'}}</option><option value="techAgriculture">{{nl?'Productievere landbouw':'More productive agriculture'}}</option><option value="lessLivestock">{{nl?'Krimp veehouderij':'Smaller livestock sector'}}</option><option value="hightechGrowth">{{nl?'Gerichte groei hightech':'Targeted high-tech growth'}}</option><option value="lessLogistics">{{nl?'Krimp logistiek':'Smaller logistics sector'}}</option></select></label>
  </header>
  <button class="block-toggle" @click="showCore=!showCore"><span><b>{{nl?'Kerninstellingen en hoofdgrafiek':'Core settings and main chart'}}</b><small>{{view==='full'?(nl?'Algemene aannames, kerncijfers en druk op de belangrijkste systeemcapaciteiten':'General assumptions, key figures and pressure on the main system capacities'):(nl?'Algemene aannames en kernuitkomsten voor dit deel van het model':'General assumptions and key outcomes for this part of the model')}}</small></span><span>{{showCore?'−':'+'}}</span></button>
  <div v-if="showCore" class="layout">
   <div class="controls">
    <template v-for="key in controls" :key="key">
     <label v-if="key==='migrationMode'" class="control"><span>{{labels.mode}}</span><select v-model="p.migrationMode"><option value="manual">{{labels.manual}}</option><option value="responsive">{{labels.responsive}}</option></select></label>
     <label v-else-if="key==='livestockTarget'" class="control"><span>{{labels.livestock}} <strong>{{fmt(p.sectorScales.livestock,1)}}%</strong></span><input v-model.number="p.sectorScales.livestock" type="range" :min="defs[key][1]" :max="defs[key][2]" :step="defs[key][3]"></label>
     <label v-else-if="key==='cropTarget'" class="control"><span>{{labels.crop}} <strong>{{fmt(p.sectorScales.crops,1)}}%</strong></span><input v-model.number="p.sectorScales.crops" type="range" :min="defs[key][1]" :max="defs[key][2]" :step="defs[key][3]"></label>
     <label v-else class="control"><span>{{labels[(defs as any)[key][0]]}} <strong>{{fmt((p as any)[key],1)}}{{['participation','unpaidDisplacement','livestockScale','cropScale','migrationResponse'].includes(key)?'%':key.includes('Growth')?'%':''}}</strong></span><input v-model.number="(p as any)[key]" type="range" :min="(defs as any)[key][1]" :max="(defs as any)[key][2]" :step="(defs as any)[key][3]"></label>
    </template>
   </div>
   <div class="results">
    <div class="metrics" :class="{'metrics-full':view==='full'}"><div v-for="card in metricCards" :key="card[0]"><span>{{card[0]}}</span><strong>{{card[1]}}</strong><small v-if="card[3]" class="baseline-delta">{{card[3]}} {{nl?'t.o.v. basispad':'vs baseline'}}</small><small class="trend" :class="`trend-${card[2]}`" :title="directionLabel(card[2])"><b aria-hidden="true">{{card[2]==='up'?'↑':card[2]==='down'?'↓':'→'}}</b> {{directionLabel(card[2])}}</small></div></div>
    <svg viewBox="0 0 600 205" role="img" :aria-label="nl?'Ontwikkeling van geselecteerde modeluitkomsten tot 2050':'Development of selected model outputs to 2050'">
     <line x1="20" y1="170" x2="580" y2="170" class="axis"/><line x1="20" y1="35" x2="20" y2="170" class="axis"/>
     <template v-if="view==='full'"><line x1="20" y1="108" x2="580" y2="108" class="capacity-line"/><polyline v-for="series in baselineSystemLoadSeries" :key="`baseline-${series.id}`" :points="systemLoadPoints(series.values)" class="system-load-line baseline-load-line" :stroke="series.color"/><polyline v-for="series in systemLoadSeries" :key="series.id" :points="systemLoadPoints(series.values)" class="system-load-line" :stroke="series.color"/><text x="24" y="103" class="capacity-label">100%</text></template>
     <template v-else-if="view==='demography'"><polyline :points="points('population',true)" class="line a"/><polyline :points="points('older',true)" class="line b"/><polyline :points="points('careDemand',true)" class="line c"/></template>
     <template v-else-if="view==='resources'"><polyline :points="points('gridDemand',true)" class="line a"/><polyline :points="points('realisedGridDemand',true)" class="line d"/><polyline :points="points('gridCapacity',true)" class="line b"/><polyline :points="points('housingGap',true,[-10,3.5])" class="line c"/></template>
     <template v-else-if="view==='agriculture'"><polyline :points="points('territorialEmissions',true)" class="line a"/><polyline :points="points('consumptionFootprint',true)" class="line b"/><polyline :points="points('landDemand',true)" class="line c"/></template>
     <template v-else><polyline :points="points('labourSupply')" class="line a"/><polyline :points="points('labourDemand')" class="line b"/></template>
     <text x="20" y="195">2025</text><text x="548" y="195">{{p.endYear}}</text>
    </svg>
    <div v-if="view==='full'" class="system-load-caption"><b>{{nl?'Systeembelasting':'System load'}}</b><span>{{nl?'100% is de beschikbare capaciteit; boven de lijn ontstaat een beperking. Doorgetrokken: huidige instellingen. Gestippeld: basispad.':'100% is available capacity; above the line a constraint emerges. Solid: current settings. Dashed: baseline.'}}</span><div class="sector-legend"><span v-for="series in systemLoadSeries" :key="series.id"><i :style="{background:series.color}"/>{{series.label}}</span></div></div><div class="legend" v-else-if="view==='demography'"><i class="a"/>{{labels.population}} <i class="b"/>{{labels.older}} <i class="c"/>{{labels.careDemand}} (2025=1)</div><div class="legend" v-else-if="view==='resources'"><i class="a"/>{{nl?'Gevraagde netcapaciteit':'Requested grid capacity'}} <i class="d"/>{{nl?'Gerealiseerd netgebruik':'Realised grid use'}} <i class="b"/>{{nl?'Netcapaciteit':'Grid capacity'}} <i class="c"/>{{labels.housing}} (2025=1)</div><div class="legend" v-else-if="view==='agriculture'"><i class="a"/>{{nl?'Territoriale uitstoot':'Territorial emissions'}} <i class="b"/>{{nl?'Consumptievoetafdruk':'Consumption footprint'}} <i class="c"/>{{nl?'Grondgebruik':'Land use'}} (2025=1)</div><div class="legend" v-else><i class="a"/>{{labels.supply}} <i class="b"/>{{labels.demand}}</div>
    <p v-if="view==='agriculture'" class="model-baseline-note">{{nl?'Referentie: bij 100% veehouderij, 100% akker- en tuinbouw en 0 technologische investering blijven de indices vlak op 100. Omvang is een doelwaarde voor 2050; de grafiek toont de geleidelijke overgang vanaf 2025. Een lagere territoriale uitstoot kan gedeeltelijk worden gecompenseerd door productie en voetafdruk buiten Nederland.':'Reference: at 100% livestock, 100% crops and horticulture and zero technology investment, the indices remain flat at 100. Scale is a 2050 target; the chart shows the gradual transition from 2025. Lower territorial emissions may be partly offset by production and footprint outside the Netherlands.'}}</p>
    <p v-if="view==='feedback'&&p.migrationMode==='responsive'" class="model-baseline-note">{{nl?'De respons verdeelt het ingestelde aandeel van het arbeidstekort uit het voorgaande jaar over een aanpassingsperiode van tien jaar. Ieder jaar wordt dus een tiende van dat aandeel aan het migratiesaldo toegevoegd, binnen de modelgrenzen van −30.000 tot 170.000 per jaar. Dit is een scenario-aanname, geen voorspelde beleidsreactie.':'The response spreads the selected share of the previous year’s labour shortage over a ten-year adjustment period. Each year, one tenth of that share is added to net migration, within the model bounds of −30,000 to 170,000 per year. This is a scenario assumption, not a predicted policy response.'}}</p>
    <div v-if="view==='full'" class="baseline-comparison"><div class="baseline-comparison-head"><b>{{nl?'Verschil in 2050 ten opzichte van het basispad':'Difference in 2050 versus baseline'}}</b><small>{{nl?'Een plus of min geeft richting aan, niet automatisch een betere of slechtere uitkomst.':'A plus or minus indicates direction, not automatically a better or worse outcome.'}}</small></div><div class="baseline-deltas"><div v-for="item in scenarioDifferences" :key="item.id"><span>{{item.label}}</span><b>{{signed(item.value,1)}}{{item.unit}}</b><small>{{Math.abs(item.value)<.05?(nl?'gelijk aan basispad':'same as baseline'):(item.value>0?(nl?'hoger dan basispad':'above baseline'):(nl?'lager dan basispad':'below baseline'))}}</small></div></div></div>
   </div>
  </div>
  <section v-if="view==='full'" class="collapsible-block"><button class="block-toggle" @click="showBalances=!showBalances"><span><b>{{nl?'Systeembalansen door de tijd':'System balances over time'}}</b><small>{{nl?'Arbeid, woningen, net, zorg, milieu en publieke financiën':'Labour, housing, grid, care, environment and public finance'}}</small></span><span>{{showBalances?'−':'+'}}</span></button><div v-if="showBalances" class="system-balances"><p>{{nl?'Iedere grafiek behoudt zijn eigen eenheid. De pijl beschrijft alleen de richting; stijgen of dalen is niet automatisch goed of slecht.':'Each chart retains its own unit. The arrow describes direction only; rising or falling is not automatically good or bad.'}}</p><div class="spark-grid"><figure v-for="series in systemSeries" :key="series.id"><figcaption>{{series.label}}</figcaption><svg viewBox="0 0 200 72"><line x1="8" y1="58" x2="192" y2="58" class="axis"/><polyline :points="sparkPoints(series.values)" class="spark-line"/><text x="8" y="70">2025</text><text x="168" y="70">{{p.endYear}}</text></svg><small><b>{{signed(series.values.at(-1)??0,1)}}</b> <span>{{directionLabel(direction(series.values[0],series.values.at(-1)??0))}}</span></small></figure></div></div></section>
  <section v-if="view==='sectors'||view==='full'" class="collapsible-block"><button class="block-toggle" @click="showSectorCharts=!showSectorCharts"><span><b>{{nl?'Sector- en financiële grafieken':'Sector and fiscal charts'}}</b><small>{{nl?'Arbeidsvraag, productiepad en publieke financiën':'Labour demand, output paths and public finance'}}</small></span><span>{{showSectorCharts?'−':'+'}}</span></button><div v-if="showSectorCharts" class="sector-charts">
   <figure><figcaption>{{nl?'Arbeidsvraag per sector':'Labour demand by sector'}}</figcaption><svg viewBox="0 0 600 205" role="img"><line x1="20" y1="170" x2="580" y2="170" class="axis"/><path v-for="s in sectorDefinitions" :key="s.id" :d="sectorAreaPath(s.id)" :fill="sectorColor(s.id)" opacity=".82"/><text x="20" y="195">2025</text><text x="548" y="195">{{p.endYear}}</text></svg></figure>
   <figure><figcaption>{{nl?'Potentiële en gerealiseerde productie (2025 = 100)':'Potential and realised output (2025 = 100)'}}</figcaption><svg viewBox="0 0 600 205" role="img"><line x1="20" y1="170" x2="580" y2="170" class="axis"/><template v-for="id in selectedSectors" :key="id"><polyline :points="sectorLinePoints(id,true)" class="sector-line potential-line" :stroke="sectorColor(id)"/><polyline :points="sectorLinePoints(id)" class="sector-line" :stroke="sectorColor(id)"/></template><text x="20" y="195">2025</text><text x="548" y="195">{{p.endYear}}</text></svg><div class="path-key"><span><i class="solid-sample"/>{{nl?'gerealiseerd':'realised'}}</span><span><i class="dashed-sample"/>{{nl?'potentieel zonder resourcegrenzen':'potential without resource limits'}}</span></div><div class="sector-legend"><span v-for="id in selectedSectors" :key="id"><i :style="{background:sectorColor(id)}"/>{{sectorName(id)}}</span></div></figure>
   <figure class="fiscal-chart"><figcaption>{{nl?'Publieke financiën door de tijd (indicatieve indexpunten)':'Public finances over time (indicative index points)'}}</figcaption><svg viewBox="0 0 600 205" role="img"><line x1="20" y1="170" x2="580" y2="170" class="axis"/><polyline :points="fiscalPoints('publicRevenue')" class="sector-line fiscal-revenue"/><polyline :points="fiscalPoints('publicCosts')" class="sector-line fiscal-cost"/><polyline :points="fiscalPoints('publicInvestment')" class="sector-line fiscal-investment"/><polyline :points="fiscalPoints('fiscalBalance')" class="sector-line fiscal-balance"/><text x="20" y="195">2025</text><text x="548" y="195">{{p.endYear}}</text></svg><div class="sector-legend"><span><i class="fiscal-revenue"/>{{nl?'inkomsten':'revenue'}}</span><span><i class="fiscal-cost"/>{{nl?'lopende lasten + steun':'running costs + support'}}</span><span><i class="fiscal-investment"/>{{nl?'investeringsbehoefte':'investment requirement'}}</span><span><i class="fiscal-balance"/>{{nl?'saldo':'balance'}}</span></div></figure>
  </div></section>
  <section v-if="view==='full'" class="collapsible-block"><button class="block-toggle" @click="showWhy=!showWhy"><span><b>{{labels.why}}</b><small>{{nl?'Toon het causale pad achter een uitkomst':'Show the causal path behind an outcome'}}</small></span><span>{{showWhy?'−':'+'}}</span></button><div v-if="showWhy" class="why"><label><span>{{nl?'Uitkomst':'Outcome'}}</span><select v-model="why"><option value="shortage">{{labels.shortage}}</option><option value="housingGap">{{labels.housing}}</option><option value="population">{{labels.population}}</option><option value="ecologyPressure">{{nl?'Milieudruk':'Environmental pressure'}}</option><option value="fiscalBalance">{{nl?'Publiek fiscaal saldo':'Public fiscal balance'}}</option></select></label><ol><li v-for="path in causalPaths(why,p)" :key="path">{{path}}</li></ol></div></section>
  <section v-if="view==='sectors'||view==='full'" class="sector-panel">
   <button class="sector-toggle" @click="showSectors=!showSectors"><span><b>{{nl?'Sectorstructuur configureren':'Configure sector structure'}}</b><small>{{nl?'Omvang, productiviteit, keteneffecten en fiscale uitkomsten':'Size, productivity, supply-chain effects and fiscal outcomes'}}</small></span><span>{{showSectors?'−':'+'}}</span></button>
   <div v-if="showSectors" class="sector-content">
    <p class="sector-help">{{nl?'Zoals in een stedenbouwsimulatie berekent het model eerst hoeveel een sector bij de gekozen vraag en productiviteit zou kunnen groeien. Schaarse capaciteit wordt vervolgens proportioneel verdeeld over de relevante vraag; de krapste gewogen hulpbron begrenst de gerealiseerde productie. Dit is een transparante verdeelregel, geen voorspelling van markt- of politieke prioriteiten. Omvang is het gewenste niveau in 2050 ten opzichte van 2025; fiscale waarden zijn modelindices, geen europrognoses.':'As in a city-building simulation, the model first calculates how far a sector could grow at the selected demand and productivity. Scarce capacity is then allocated proportionally across relevant demand; the tightest weighted resource limits realised output. This is a transparent allocation rule, not a prediction of market or political priorities. Size is the desired 2050 level relative to 2025; fiscal values are model indices, not euro forecasts.'}}</p>
    <div class="resource-status"><div v-for="resource in resourceCards" :key="resource.id" :class="{limited:resource.limited}"><span>{{resource.label}}</span><b>{{fmt(resource.value,1)}}%</b><small>{{resource.limited?(nl?'beschikbaar t.o.v. potentiële vraag':'available relative to potential demand'):(nl?'geen systeembrede beperking':'no system-wide constraint')}}</small></div></div>
    <aside class="live-impact"><div class="live-impact-head"><span>{{nl?'Live-effecten voor':'Live effects for'}} <b>{{sectorName(activeSector)}}</b></span><small>{{nl?'Lijn: ontwikkeling door de tijd · vergelijking: dezelfde configuratie met deze sector op 100%':'Line: development over time · comparison: same configuration with this sector at 100%'}}</small></div><div class="live-sparks"><figure v-for="series in activeSectorSeries" :key="series.id"><figcaption>{{series.label}}</figcaption><svg viewBox="0 0 200 72"><line x1="8" :y1="series.id==='headroom'?sparkZeroY(series.values):58" x2="192" :y2="series.id==='headroom'?sparkZeroY(series.values):58" class="axis" :class="{'zero-axis':series.id==='headroom'}"/><polyline :points="sparkPoints(series.values,series.id==='headroom')" class="spark-line"/><text x="8" y="70">2025</text><text x="168" y="70">{{p.endYear}}</text></svg><div class="live-values"><span><b>{{p.endYear}}:</b> {{['fiscal','housing','total','headroom'].includes(series.id)?signed(series.values.at(-1)??0,1):fmt(series.values.at(-1)??0,1)}}</span><span><b>{{nl?'t.o.v. 100%':'vs 100%' }}:</b> {{signed((series.values.at(-1)??0)-series.referenceEnd,1)}}</span><span>{{directionLabel(direction(series.values[0],series.values.at(-1)??0))}} {{nl?'door de tijd':'over time'}}</span></div></figure></div><p v-if="activeSector==='livestock'||activeSector==='crops'" class="housing-impact-note">{{nl?`In ${p.endYear} maakt het systeem ${fmt(last.availableHousebuildingCapacity/1000,1)} duizend woningen technisch mogelijk en worden er ${fmt(last.realisedHousebuilding/1000,1)} duizend gerealiseerd. De actuele begrenzing is ${constraintLabel(last.housingConstraint)}.`:`In ${p.endYear}, the system technically allows ${fmt(last.availableHousebuildingCapacity/1000,1)} thousand homes and realises ${fmt(last.realisedHousebuilding/1000,1)} thousand. The current constraint is ${constraintLabel(last.housingConstraint)}.`}}</p></aside>
    <div class="sector-config">
     <article v-for="(s,index) in sectorDefinitions" :key="s.id" class="sector-card" :class="{active:s.id===activeSector}" :style="{'--sector':palette[index]}" @click="activeSector=s.id">
      <div class="sector-head"><label><input type="checkbox" :checked="selectedSectors.includes(s.id)" @change="toggleSector(s.id)"><span>{{nl?s.nl:s.en}}</span></label><strong>{{fmt(p.sectorScales[s.id])}}%</strong></div>
      <button class="show-sector-effects" type="button" :aria-pressed="s.id===activeSector" @click.stop="activeSector=s.id">{{s.id===activeSector?(nl?'Effecten worden hierboven getoond':'Effects shown above'):(nl?'Toon live-effecten':'Show live effects')}}</button>
      <label><span>{{nl?'Omvang in 2050':'Size in 2050'}}</span><input v-model.number="p.sectorScales[s.id]" type="range" min="40" max="160" step="5" @input="activeSector=s.id"></label>
      <label><span>{{nl?'Eigen productiviteitsgroei':'Own productivity growth'}} {{fmt(p.sectorProductivity[s.id],1)}}%</span><input v-model.number="p.sectorProductivity[s.id]" type="range" min="0" max="3" step=".1" @input="activeSector=s.id"></label>
      <div class="sector-outcome"><span>{{nl?'Potentieel zonder resourcegrenzen':'Potential without resource limits'}} <b>{{fmt(last.sectors[s.id].potentialOutput)}}</b></span><span>{{nl?'Gerealiseerde productie-index':'Realised output index'}} <b>{{fmt(last.sectors[s.id].output)}}</b></span><span>{{nl?'Resourcebeperking':'Resource constraint'}} <b>{{fmt((1-last.sectors[s.id].resourceConstraint)*100,1)}}%</b></span><span>{{nl?'Bottleneck':'Bottleneck'}} <b>{{resourceLabel(last.sectors[s.id].bottleneck)}}</b></span><span>{{nl?'Arbeidsvraag 2050':'Labour demand 2050'}} <b>{{millions(last.sectors[s.id].labourDemand)}}</b></span><span>{{nl?'Fiscaal saldo-index':'Fiscal balance index'}} <b>{{fmt(last.sectors[s.id].fiscalBalance,1)}}</b></span><span v-if="Math.abs(last.sectors[s.id].chainEffect-1)>.001">{{nl?'Keteneffect':'Supply-chain effect'}} <b>{{last.sectors[s.id].chainEffect>1?'+':''}}{{fmt((last.sectors[s.id].chainEffect-1)*100,1)}}%</b></span></div>
      <small>{{nl?'Arbeidsaandeel startjaar':'Base-year labour share'}} {{fmt(s.labour*100,1)}}% · {{nl?'binnenlandse vraag':'domestic demand'}} {{fmt(s.domestic*100)}}%</small>
     </article>
    </div>
   </div>
  </section>
  <section v-if="view==='full'" class="sector-panel land-panel">
   <button class="sector-toggle" @click="showLand=!showLand"><span><b>{{nl?'Grond, vergunningen en woningbouw':'Land, permits and housebuilding'}}</b><small>{{nl?'Van minder landbouwdruk naar potentiële en gerealiseerde bouwruimte':'From reduced agricultural pressure to potential and realised building capacity'}}</small></span><span>{{showLand?'−':'+'}}</span></button>
   <div v-if="showLand" class="sector-content">
    <p class="sector-help">{{nl?'Vrijgekomen landbouwgrond wordt niet automatisch bouwgrond. Het model past achtereenvolgens geschiktheid, politieke toedeling, vergunningruimte, ontsluiting en uitvoeringscapaciteit toe. De laagste capaciteit begrenst de gerealiseerde woningbouw.':'Released agricultural land does not automatically become building land. The model successively applies suitability, policy allocation, permit capacity, servicing and delivery capacity. The lowest capacity limits realised housebuilding.'}}</p>
    <div class="allocation-grid"><label :class="{inactive:last.releasedAgriculturalLand<=.01}"><span>{{nl?'Potentieel converteerbaar aandeel':'Potentially convertible share'}} <b>{{fmt(p.landConversionShare)}}%</b></span><input v-model.number="p.landConversionShare" type="range" min="0" max="40" step="1" :disabled="last.releasedAgriculturalLand<=.01"><small v-if="last.releasedAgriculturalLand<=.01">{{nl?'Geen effect zolang geen landbouwgrond vrijkomt.':'No effect until agricultural land is released.'}}</small></label><label :class="{inactive:last.releasedAgriculturalLand<=.01}"><span>{{nl?'Aandeel daarvan voor wonen':'Share allocated to housing'}} <b>{{fmt(p.releasedLandHousingShare)}}%</b></span><input v-model.number="p.releasedLandHousingShare" type="range" min="0" max="80" step="2" :disabled="last.releasedAgriculturalLand<=.01"><small v-if="last.releasedAgriculturalLand<=.01">{{nl?'Verlaag eerst akkerbouw of veehouderij.':'First reduce crops or livestock.'}}</small></label><label><span>{{nl?'Ontsluiting water/net/infrastructuur':'Water/grid/infrastructure readiness'}} <b>{{fmt(p.infrastructureReadiness)}}%</b></span><input v-model.number="p.infrastructureReadiness" type="range" min="50" max="130" step="5"></label><label :class="{inactive:Math.abs(last.ecologyPressure-100)<.1}"><span>{{nl?'Gevoeligheid vergunningruimte voor stikstofdruk':'Permit sensitivity to nitrogen pressure'}} <b>{{fmt(p.nitrogenPermitSensitivity)}}%</b></span><input v-model.number="p.nitrogenPermitSensitivity" type="range" min="0" max="100" step="5" :disabled="Math.abs(last.ecologyPressure-100)<.1"><small v-if="Math.abs(last.ecologyPressure-100)<.1">{{nl?'Geen effect zolang de milieudruk op de referentiewaarde blijft.':'No effect while environmental pressure remains at its reference value.'}}</small></label></div>
    <div class="fiscal-summary housing-capacity-summary"><div><span>{{nl?'Vrijgekomen landbouwgrond-index':'Released agricultural-land index'}}</span><b>{{fmt(last.releasedAgriculturalLand,1)}}</b></div><div><span>{{nl?'Capaciteit geschikte bouwgrond':'Suitable-land capacity'}}</span><b>{{fmt(last.housingLandCapacity/1000)}}k</b></div><div><span>{{nl?'Vergunningscapaciteit':'Permit capacity'}}</span><b>{{fmt(last.permitCapacity/1000)}}k</b></div><div><span>{{nl?'Ontsloten capaciteit':'Serviced capacity'}}</span><b>{{fmt(last.infrastructureCapacity/1000)}}k</b></div><div><span>{{nl?'Gerealiseerde woningbouw':'Realised housebuilding'}}</span><b>{{fmt(last.realisedHousebuilding/1000)}}k</b></div><div><span>{{nl?'Beperkende factor':'Limiting factor'}}</span><b>{{constraintLabel(last.housingConstraint)}}</b></div></div>
   </div>
  </section>
  <section v-if="view==='full'" class="sector-panel public-panel">
   <button class="sector-toggle" @click="showPublic=!showPublic"><span><b>{{nl?'Publieke financiën en investeringen':'Public finances and investment'}}</b><small>{{nl?'Verdeel fiscale ruimte zonder maatschappelijke waarde tot één score te reduceren':'Allocate fiscal space without reducing social value to one score'}}</small></span><span>{{showPublic?'−':'+'}}</span></button>
   <div v-if="showPublic" class="sector-content">
    <label class="control"><span>{{nl?'Relatieve effectieve belastingopbrengst':'Relative effective tax capture'}} <strong>{{fmt(p.taxCapture)}}%</strong></span><input v-model.number="p.taxCapture" type="range" min="70" max="130" step="5"></label>
    <p class="sector-help">{{nl?'De onderstaande waarden zijn verdelingsgewichten en worden automatisch genormaliseerd tot 100%. Meer fiscale ruimte versterkt toekomstige capaciteit; minder ruimte remt die. De behoefte aan publieke diensten blijft afzonderlijk berekend.':'The values below are allocation weights and are automatically normalised to 100%. More fiscal space strengthens future capacity; less space slows it. Need for public services is still calculated separately.'}}</p>
    <div class="allocation-grid"><label v-for="item in [['housing','Woningen','Housing'],['grid','Elektriciteitsnet','Electricity grid'],['care','Zorg','Healthcare'],['education','Onderwijs','Education'],['safety','Overheid en veiligheid','Government and safety'],['nature','Natuurherstel','Nature restoration'],['reserve','Buffer/schuld','Buffer/debt']]" :key="item[0]"><span>{{nl?item[1]:item[2]}} <b>{{allocationPct(item[0])}}%</b></span><input v-model.number="p.publicAllocation[item[0]]" type="range" min="0" max="40" step="1"></label></div>
    <div class="fiscal-summary"><div><span>{{nl?'Publieke inkomsten':'Public revenue'}}</span><b>{{fmt(last.publicRevenue,1)}}</b></div><div><span>{{nl?'Lopende lasten en steun':'Running costs and support'}}</span><b>{{fmt(last.publicCosts,1)}}</b></div><div><span>{{nl?'Investeringsbehoefte':'Investment requirement'}}</span><b>{{fmt(last.publicInvestment,1)}}</b></div><div><span>{{nl?'Indicatief saldo':'Indicative balance'}}</span><b>{{fmt(last.fiscalBalance,1)}}</b></div></div>
   </div>
  </section>
  <button class="registry-button" @click="showRegister=!showRegister">{{labels.registry}} {{showRegister?'−':'+'}}</button>
  <div v-if="showRegister" class="registry"><div v-for="row in register" :key="row.key"><b>{{row.kind}}</b><span>{{row.key}}: {{row.value}}</span><small>{{row.source}}</small></div></div>
  <p class="caveat">{{nl?'Illustratieve systeemverkenning, geen voorspelling. Waarnemingen, afleidingen en aannames zijn apart gelabeld.':'Illustrative system exploration, not a forecast. Observations, derivations and assumptions are labelled separately.'}}</p>
 </section>
</template>

<style scoped>
.explorer{--ink:#17352e;--soft:#eef3ef;width:min(1400px,calc(100vw - 48px));max-width:none;margin:2rem 0 2rem 50%;transform:translateX(-50%);border:1px solid #bdcbc5;border-radius:22px;background:#fbfcfa;padding:clamp(1rem,3vw,2rem);color:var(--ink);box-shadow:0 12px 35px #2344380a}.explorer header{display:flex;justify-content:space-between;gap:1.5rem;align-items:end}.explorer h3{margin:.1rem 0;font-size:clamp(1.45rem,3vw,2rem)}.explorer header p{margin:.3rem 0;max-width:650px}.eyebrow{font-size:.68rem;letter-spacing:.12em;font-weight:800;color:#7a4d30}.scenario,.control{display:grid;gap:.35rem}.scenario select,.control select{border:1px solid #aabbb4;border-radius:9px;background:white;padding:.55rem}.layout{display:grid;grid-template-columns:minmax(230px,.72fr) minmax(0,1.4fr);gap:1.2rem;margin-top:1.3rem}.controls{background:var(--soft);border-radius:15px;padding:1rem;display:grid;gap:.9rem;align-content:start}.control span{display:flex;justify-content:space-between;gap:1rem;font-size:.88rem}.control input{width:100%;accent-color:#225e52}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:.5rem}.metrics div{background:#f1f3ee;padding:.65rem;border-radius:10px;min-width:0}.metrics span{display:block;font-size:.72rem;color:#5f6e69}.metrics strong{display:block;font-size:1.12rem;margin-top:.25rem}.metrics .baseline-delta{display:block;margin-top:.2rem;color:#3f665e;font-size:.62rem;font-weight:700}.warn{color:#a04732}.results svg{width:100%;height:auto;margin-top:.5rem}.axis{stroke:#b5c0bb}.line{fill:none;stroke-width:5;stroke-linecap:round;stroke-linejoin:round}.line.a,.legend i.a{stroke:#2e7165;background:#2e7165}.line.b,.legend i.b{stroke:#c07b3c;background:#c07b3c}.results text{font-size:13px;fill:#61706b}.legend{display:flex;align-items:center;gap:.5rem;font-size:.8rem;flex-wrap:wrap}.legend i{display:inline-block;width:20px;height:4px;margin-left:.45rem}.why{margin-top:1rem;padding:1rem;background:#f6efe7;border-radius:14px}.why label{display:flex;justify-content:space-between;font-weight:700}.why select{padding:.35rem}.why ol{margin-bottom:0}.registry-button{margin-top:1rem;border:0;background:transparent;color:#275f55;text-decoration:underline;cursor:pointer;padding:0}.registry{display:grid;gap:.4rem;margin-top:.8rem}.registry div{display:grid;grid-template-columns:130px 1fr 1fr;gap:.6rem;padding:.55rem;background:#eef1ed;border-radius:8px;font-size:.78rem}.registry b{text-transform:uppercase;font-size:.65rem;letter-spacing:.06em}.caveat{font-size:.78rem;color:#66736e;margin-bottom:0}@media(max-width:720px){.explorer{width:calc(100vw - 32px)}.explorer header,.layout{display:block}.scenario{margin-top:1rem}.controls{margin-bottom:1rem}.metrics{grid-template-columns:1fr 1fr}.registry div{grid-template-columns:1fr}.registry small{color:#64716d}}
.sector-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:.45rem;margin-top:1rem}.sector-grid div{display:grid;padding:.6rem;background:#eef1ed;border-radius:9px;font-size:.7rem}.sector-grid b{font-size:.76rem;margin-bottom:.25rem}.sector-grid span{color:#64716d}
.line.c,.legend i.c{stroke:#745895;background:#745895}
.line.d,.legend i.d{stroke:#3f78a1;background:#3f78a1}
.sector-panel{margin-top:1rem;border:1px solid #bdcbc5;border-radius:15px;overflow:hidden}.sector-toggle{width:100%;display:flex;justify-content:space-between;align-items:center;border:0;background:#e8efeb;padding:1rem 1.1rem;color:var(--ink);text-align:left;cursor:pointer}.sector-toggle span:first-child{display:grid}.sector-toggle small{font-weight:400;color:#64716d;margin-top:.15rem}.sector-content{padding:1rem}.sector-help{margin-top:0;font-size:.86rem;color:#5e6d68}.sector-config{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:.55rem}.sector-card{border:1px solid transparent;border-left:5px solid var(--sector);background:#f2f4f0;border-radius:9px;padding:.7rem;display:grid;gap:.5rem;cursor:pointer;transition:background .15s,border-color .15s,box-shadow .15s}.sector-card.active{background:#fff;border-color:var(--sector);border-left-width:5px;box-shadow:0 0 0 2px color-mix(in srgb,var(--sector) 18%,transparent)}.sector-card label{display:grid;gap:.2rem;font-size:.72rem}.sector-card input[type=range]{width:100%;accent-color:var(--sector)}.sector-head{display:flex;align-items:center;justify-content:space-between;gap:.6rem}.sector-head label{display:flex;align-items:center;font-size:.83rem;font-weight:700}.show-sector-effects{justify-self:start;border:0;background:transparent;color:#38675e;text-decoration:underline;text-underline-offset:2px;padding:0;font:inherit;font-size:.65rem;cursor:pointer}.sector-card.active .show-sector-effects{color:var(--ink);text-decoration:none;font-weight:700}.sector-card small{color:#697671;font-size:.65rem}.sector-charts{display:grid;grid-template-columns:1fr 1fr;gap:.8rem;margin-top:1rem}.sector-charts figure{margin:0;background:#fafbf9;border:1px solid #d6ded9;border-radius:11px;padding:.65rem}.sector-charts figcaption{font-weight:700;font-size:.82rem}.sector-charts svg{width:100%;height:auto}.sector-charts text{font-size:13px;fill:#61706b}.sector-line{fill:none;stroke-width:5;stroke-linecap:round;stroke-linejoin:round}.sector-legend{display:flex;flex-wrap:wrap;gap:.55rem;font-size:.68rem}.sector-legend span{display:flex;align-items:center;gap:.25rem}.sector-legend i{width:14px;height:4px}@media(max-width:720px){.sector-charts{grid-template-columns:1fr}.sector-config{grid-template-columns:1fr}}
.sector-outcome{display:grid;gap:.12rem;border-top:1px solid #d9dfdb;padding-top:.4rem;font-size:.67rem}.sector-outcome span{display:flex;justify-content:space-between;gap:.5rem}
.potential-line{stroke-dasharray:8 7;stroke-width:2.5;opacity:.55}.path-key{display:flex;gap:1rem;flex-wrap:wrap;margin:.25rem 0 .55rem;font-size:.66rem;color:#65736e}.path-key span{display:flex;align-items:center;gap:.3rem}.path-key i{display:inline-block;width:24px;border-top:3px solid #536f88}.path-key .dashed-sample{border-top-style:dashed;opacity:.65}.resource-status{display:grid;grid-template-columns:repeat(5,1fr);gap:.45rem;margin:.7rem 0}.resource-status div{display:grid;gap:.12rem;padding:.6rem;background:#edf3ef;border-radius:9px;border-top:4px solid #5a897f}.resource-status div.limited{background:#f5eee5;border-color:#b9783e}.resource-status span{font-size:.67rem}.resource-status b{font-size:1rem}.resource-status small{font-size:.58rem;color:#65736e}@media(max-width:720px){.resource-status{grid-template-columns:1fr 1fr}}@media(max-width:430px){.resource-status{grid-template-columns:1fr}}
.system-load-line{fill:none;stroke-width:4;stroke-linecap:round;stroke-linejoin:round}.baseline-load-line{stroke-width:2;stroke-dasharray:7 6;opacity:.45}.capacity-line{stroke:#8b5a45;stroke-width:2;stroke-dasharray:7 6}.results text.capacity-label{font-size:11px;fill:#8b5a45}.system-load-caption{display:grid;gap:.3rem;padding:.55rem .65rem;background:#f1f3ee;border-radius:9px;font-size:.72rem}.system-load-caption>span{color:#63716c}.system-load-caption .sector-legend{margin-top:.15rem}.baseline-comparison{margin-top:.65rem;padding:.75rem;background:#edf2ef;border:1px solid #d1ddd7;border-radius:10px}.baseline-comparison-head{display:flex;justify-content:space-between;gap:1rem;align-items:baseline}.baseline-comparison-head small{color:#63716c;font-size:.62rem}.baseline-deltas{display:grid;grid-template-columns:repeat(3,1fr);gap:.4rem;margin-top:.55rem}.baseline-deltas>div{display:grid;padding:.55rem;background:#fff;border-radius:8px}.baseline-deltas span{color:#63716c;font-size:.62rem}.baseline-deltas b{font-size:.9rem}.baseline-deltas small{font-size:.58rem;color:#66736e}@media(max-width:720px){.baseline-comparison-head{display:grid}.baseline-deltas{grid-template-columns:1fr 1fr}}@media(max-width:430px){.baseline-deltas{grid-template-columns:1fr}}
.model-baseline-note{margin:.7rem 0 0;padding:.65rem .75rem;background:#f6efe7;border-left:3px solid #a56c43;color:#5f6d68;font-size:.7rem;line-height:1.5}
.fiscal-chart{grid-column:1/-1}.fiscal-revenue{stroke:#2e7165;background:#2e7165}.fiscal-cost{stroke:#a44d42;background:#a44d42}.fiscal-investment{stroke:#c28a3c;background:#c28a3c}.fiscal-balance{stroke:#574778;background:#574778}.allocation-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:.65rem}.allocation-grid label{display:grid;gap:.25rem;font-size:.75rem}.allocation-grid label.inactive{opacity:.58}.allocation-grid span{display:flex;justify-content:space-between}.allocation-grid input{width:100%;accent-color:#28685e}.allocation-grid small{color:#66736e;font-size:.62rem;line-height:1.35}.fiscal-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:.5rem;margin-top:1rem}.fiscal-summary div{display:grid;background:#eef1ed;padding:.7rem;border-radius:9px}.fiscal-summary span{font-size:.67rem;color:#63716c}.fiscal-summary b{font-size:1rem;margin-top:.2rem}@media(max-width:720px){.fiscal-summary{grid-template-columns:1fr 1fr}}
.metrics small.trend{display:flex;align-items:center;gap:.25rem;margin-top:.25rem;font-size:.64rem;color:#65746f}.metrics small.trend b{font-size:.9rem;color:#536f88}.trend-down b{transform:translateY(1px)}.metrics-full{grid-template-columns:repeat(4,1fr)}.system-balances{margin-top:1rem;background:#f2f4f0;border-radius:14px;padding:1rem}.system-balances h4{margin:0;font-size:1rem}.system-balances>p{font-size:.75rem;color:#66736e;margin:.3rem 0 .8rem}.spark-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.55rem}.spark-grid figure{margin:0;background:#fff;border:1px solid #d5ddd8;border-radius:9px;padding:.55rem}.spark-grid figcaption{font-size:.68rem;font-weight:700;min-height:2.2em}.spark-grid svg{width:100%;height:auto}.spark-grid text{font-size:8px;fill:#6b7873}.spark-line{fill:none;stroke:#536f88;stroke-width:3;stroke-linecap:round;stroke-linejoin:round}.spark-grid small{display:flex;justify-content:space-between;font-size:.64rem;color:#697671}.spark-grid small b{font-size:.72rem;color:var(--ink)}@media(max-width:720px){.metrics-full{grid-template-columns:1fr 1fr}.spark-grid{grid-template-columns:1fr 1fr}}@media(max-width:430px){.spark-grid{grid-template-columns:1fr}}
.collapsible-block{margin-top:1rem;border:1px solid #bdcbc5;border-radius:15px;overflow:hidden}.block-toggle{width:100%;display:flex;justify-content:space-between;align-items:center;border:0;background:#edf1ee;padding:.9rem 1.05rem;color:var(--ink);text-align:left;cursor:pointer}.block-toggle span:first-child{display:grid}.block-toggle small{font-weight:400;color:#64716d;margin-top:.12rem}.live-impact{position:sticky;top:.5rem;z-index:2;background:#e7eeea;border:1px solid #afc1b9;border-radius:12px;padding:.75rem;margin-bottom:.8rem;box-shadow:0 5px 18px #17352e12}.live-impact-head{display:flex;justify-content:space-between;gap:1rem;font-size:.8rem}.live-impact-head small{color:#65736e}.live-sparks{display:grid;grid-template-columns:repeat(4,1fr);gap:.45rem;margin-top:.55rem}.live-sparks figure{margin:0;background:#fff;border-radius:8px;padding:.4rem}.live-sparks figcaption{font-size:.62rem;font-weight:700;min-height:2em}.live-sparks svg{width:100%;height:auto}.live-sparks text{font-size:8px;fill:#6b7873}.live-sparks small{display:flex;justify-content:space-between;font-size:.6rem;color:#65736e}@media(max-width:720px){.live-impact{position:static}.live-sparks{grid-template-columns:1fr 1fr}.live-impact-head{display:grid}}
.live-values{display:grid;gap:.12rem;font-size:.58rem;color:#65736e}.live-values span{display:flex;justify-content:space-between;gap:.35rem}.live-values b{color:var(--ink)}
.housing-impact-note{margin:.6rem 0 0;padding:.55rem .65rem;background:#fff;border-left:3px solid #53766d;color:#50625d;font-size:.68rem;line-height:1.45}
</style>
