<script setup lang="ts">
const props=withDefaults(defineProps<{locale?:'nl'|'en';mode?:'overview'|'proposal'}>(),{locale:'nl',mode:'overview'})
const nl=computed(()=>props.locale==='nl')
const scenarios=computed(()=>[
 {name:nl.value?'Meteen betalen':'Pay immediately',timing:nl.value?'Voor of bij verzending':'Before or at shipment',credit:nl.value?'Geen krediet bij eigen geld':'No credit when using owned funds',risk:nl.value?'Geld is al overgemaakt wanneer levering uitblijft of fraude blijkt.':'Funds have already moved if delivery fails or fraud occurs.',solution:nl.value?'Controleer eigen geld en reken direct af. Herstel blijft via betwisting of terugboeking lopen.':'Check owned funds and settle immediately. Recovery still requires a dispute or reversal.'},
 {name:nl.value?'Echte creditcard':'Credit card',timing:nl.value?'Kredietruimte wordt direct gereserveerd; afschrijving volgt later':'Credit is reserved immediately; collection follows later',credit:nl.value?'Tijdelijk krediet, ook bij maandelijkse aflossing':'Temporary credit, even when repaid monthly',risk:nl.value?'Schuld ontstaat direct; chargeback biedt mogelijke maar geen automatische bescherming.':'Debt arises immediately; chargeback offers possible, not automatic, protection.',solution:nl.value?'Laat de autorisatie direct meetellen als gebruikte kredietruimte, zonder dezelfde verplichting dubbel te boeken.':'Count authorisation immediately as used credit capacity without recording the same obligation twice.'},
 {name:nl.value?'Uitgesteld betalen':'Deferred payment',timing:nl.value?'Op een vooraf vastgelegde latere datum':'On a fixed later date',credit:nl.value?'Gewoonlijk krediet tot de afrekening':'Usually credit until settlement',risk:nl.value?'Toekomstige afschrijvingen en kosten bij te laat betalen zijn niet altijd goed zichtbaar.':'Future collections and late-payment costs may not be clearly visible.',solution:nl.value?'Reserveer eigen geld waar mogelijk en laat ieder ongedekt bedrag direct de kredietruimte verminderen.':'Reserve owned funds where possible and let every uncovered amount reduce credit capacity immediately.'},
 {name:nl.value?'Betalen bij levering':'Pay on delivery',timing:nl.value?'Bij aanvaarde overdracht':'Upon accepted handover',credit:nl.value?'Alleen via een kredietbetaalmiddel':'Only through a credit payment method',risk:nl.value?'Minder vooruitbetalingsrisico, maar inhoud en kwaliteit zijn niet altijd direct controleerbaar.':'Less prepayment risk, but contents and quality may not be immediately verifiable.',solution:nl.value?'Blokkeer het bedrag vooraf, maak het bij aanvaarding over en geef het bij vervallen levering weer vrij.':'Block the amount in advance, transfer it upon acceptance and release it when delivery is cancelled.'},
 {name:nl.value?'Achteraf binnen een termijn':'Pay after delivery',timing:nl.value?'Na levering, bijvoorbeeld binnen 14 of 30 dagen':'After delivery, for example within 14 or 30 days',credit:nl.value?'Openstaande vordering tot de afrekening':'Outstanding claim until settlement',risk:nl.value?'De verplichting blijft open en kan bij een gemiste termijn duurder worden.':'The obligation remains outstanding and may become more expensive after a missed deadline.',solution:nl.value?'Blokkeer eigen geld tot afrekening of gebruik krediet voor het ongedekte deel. Een blokkade geeft betalingszekerheid, maar bepaalt niet alleen de juridische kwalificatie.':'Block owned funds until settlement or use credit for the uncovered share. A hold provides payment assurance but does not by itself determine the legal classification.'},
 {name:nl.value?'Gespreid betalen':'Instalments',timing:nl.value?'In meerdere termijnen':'In several instalments',credit:nl.value?'Krediet voor het niet vooraf gedekte deel':'Credit for the share not funded in advance',risk:nl.value?'Langere looptijd, mogelijke rente en stapeling met andere verplichtingen.':'Longer duration, possible interest and stacking with other obligations.',solution:nl.value?'Maak alle termijnen vooraf zichtbaar; gereserveerd eigen geld dekt termijnen, de resterende hoofdsom belast kredietruimte.':'Show every instalment in advance; reserved owned funds cover instalments and remaining principal consumes credit capacity.'}
])
</script>

<template>
 <section class="scenario-grid" :aria-label="mode==='overview'?(nl?'Vergelijking van betaalvormen':'Comparison of payment methods'):(nl?'Verwerking in het voorgestelde systeem':'Treatment in the proposed system')">
  <article v-for="(item,index) in scenarios" :key="item.name">
   <header><span>{{String(index+1).padStart(2,'0')}}</span><h4>{{item.name}}</h4></header>
   <template v-if="mode==='overview'">
    <dl><div><dt>{{nl?'Betaalmoment':'Payment timing'}}</dt><dd>{{item.timing}}</dd></div><div><dt>{{nl?'Krediet':'Credit'}}</dt><dd>{{item.credit}}</dd></div><div><dt>{{nl?'Belangrijkste risico':'Main risk'}}</dt><dd>{{item.risk}}</dd></div></dl>
   </template>
   <p v-else>{{item.solution}}</p>
  </article>
 </section>
</template>

<style scoped>
.scenario-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.8rem;margin:1.25rem 0 1.75rem}.scenario-grid article{min-width:0;padding:1rem;background:#f6f5ef;border:1px solid #d9ddd8;border-radius:12px}.scenario-grid header{display:flex;gap:.6rem;align-items:baseline;margin-bottom:.65rem}.scenario-grid header span{color:#a34e37;font-size:.65rem;font-weight:800;letter-spacing:.08em}.scenario-grid h4{margin:0;color:#17302b;font-size:.95rem;line-height:1.25}.scenario-grid dl,.scenario-grid p{margin:0}.scenario-grid dl{display:grid;gap:.55rem}.scenario-grid dl div{padding-top:.5rem;border-top:1px solid #dde1dc}.scenario-grid dt{color:#687570;font-size:.62rem;font-weight:800;letter-spacing:.05em;text-transform:uppercase}.scenario-grid dd,.scenario-grid p{margin:.15rem 0 0;color:#334b46;font-size:.74rem;line-height:1.48}@media(max-width:850px){.scenario-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.scenario-grid{grid-template-columns:1fr;gap:.6rem}.scenario-grid article{padding:.85rem}.scenario-grid dl{gap:.4rem}}
</style>
