export type DancerId='a'|'b'
export type MovementId='side-step'|'forward-step'|'cruce'|'forward-ocho'|'backward-ocho'|'giro'
export type Point={x:number;y:number}
export type FootState=Point&{angle:number;load:number;clearance?:number}
export type DancerState={torso:Point;angle:number;pelvisAngle:number;left:FootState;right:FootState}
export type Contact={type:'hand'|'arm'|'torso';a:Point;b:Point;active:number}
export type Phase='available'|'proposal'|'projection'|'transfer'|'pivot'|'arrival'
export type Embrace='open'|'half-open'|'closed'
export type TangoFrame={a:DancerState;b:DancerState;contacts:Contact[];phase:Phase;noteNl:string;noteEn:string;progress:number}
type Keyframe=Omit<TangoFrame,'progress'>&{at:number}
export type SequenceCheckpoint={at:number;nameNl:string;nameEn:string;supportNl:string;supportEn:string;techniquesNl:string[];techniquesEn:string[];routesNl:string[];routesEn:string[]}
export type Movement={id:MovementId;nameNl:string;nameEn:string;initiator:DancerId|'shared';systemNl:string;systemEn:string;sequenceNl:string[];sequenceEn:string[];keyframes:Keyframe[];next:MovementId[];checkpoints?:SequenceCheckpoint[]}
export type LegJoints={hip:Point;knee:Point;ankle:Point;reachable:boolean}
export type BiomechanicalCheck={id:'reach'|'torsion'|'load'|'clearance'|'balance'|'support'|'orientation'|'connection'|'direction';ok:boolean;labelNl:string;labelEn:string}

export const BODY_LIMITS={hipHalfWidth:13,thighLength:64,shinLength:64,maxTorsoPelvisTwist:68,minFootClearance:12,maxSupportDistance:118} as const
export const PARTNER_LIMITS={maxTorsoSeparation:205,maxFacingError:85} as const

const f=(x:number,y:number,angle:number,load:number):FootState=>({x,y,angle,load})
const d=(x:number,y:number,angle:number,left:FootState,right:FootState,pelvisAngle=angle):DancerState=>({torso:{x,y},angle,pelvisAngle,left,right})
const cs=(a:DancerState,b:DancerState,n=1):Contact[]=>[
 {type:'hand',a:{x:a.torso.x+8,y:a.torso.y-42},b:{x:b.torso.x-8,y:b.torso.y-42},active:n},
 {type:'arm',a:{x:a.torso.x+12,y:a.torso.y+34},b:{x:b.torso.x-12,y:b.torso.y+34},active:n*.85},
 {type:'torso',a:{x:a.torso.x+23,y:a.torso.y},b:{x:b.torso.x-23,y:b.torso.y},active:n*.45}]
const k=(at:number,phase:Phase,nl:string,en:string,a:DancerState,b:DancerState,n=1):Keyframe=>({at,phase,noteNl:nl,noteEn:en,a,b,contacts:cs(a,b,n)})
const sideA=d(330,250,0,f(310,232,0,0),f(310,268,0,1)),sideB=d(470,250,180,f(490,268,180,1),f(490,232,180,0))
const walkA=d(330,250,0,f(310,232,0,1),f(310,268,0,0)),walkB=d(470,250,180,f(490,268,180,0),f(490,232,180,1))

export const tangoMovements:Movement[]=[
 {id:'side-step',nameNl:'Zijstap',nameEn:'Side step',initiator:'a',systemNl:'parallel systeem',systemEn:'parallel system',sequenceNl:['A geeft torso-impuls links','B projecteert als antwoord','A projecteert en stapt','gewicht volgt','rechterbeen sluit aan'],sequenceEn:['A gives a leftward torso impulse','B projects in response','A projects and steps','weight follows','right leg closes'],next:['forward-step','forward-ocho','cruce'],keyframes:[
  k(0,'available','De stapvoeten zijn vrij: A draagt rechts, B links.','The stepping feet are free: A is supported on the right, B on the left.',sideA,sideB),
  k(.14,'proposal','Initiatief A: alleen A’s bovenlijf geeft een impuls naar links; de stapvoet blijft staan.','A initiates: only A’s upper body gives a leftward impulse; the stepping foot remains in place.',d(330,238,0,f(310,232,0,0),f(310,268,0,1)),sideB),
  k(.32,'projection','B antwoordt door de rechtervoet zijwaarts te projecteren, terwijl A nog niet stapt.','B responds by projecting the right foot sideways while A has not yet stepped.',d(330,234,0,f(310,232,0,0),f(310,268,0,1)),d(470,246,180,f(490,268,180,1),f(490,188,180,0))),
  k(.44,'proposal','Beslismoment: zonder vervolgimpuls kan B de projectie intrekken — een mogelijke amague. A zet hier het voorstel door.','Decision point: without a continuing impulse B can retract the projection—a possible amague. Here A continues the proposal.',d(330,224,0,f(310,232,0,0),f(310,268,0,1)),d(470,238,180,f(490,268,180,1),f(490,166,180,0))),
  k(.6,'projection','Nu projecteert A zelf links. Beide vrije voeten blijven in de lichaamsrichting georiënteerd.','A now projects the left foot. Both free feet remain oriented with the body.',d(330,214,0,f(310,164,0,0),f(310,268,0,1)),d(470,218,180,f(490,268,180,1),f(490,160,180,0))),
  k(.74,'projection','Beide stapvoeten zijn geplaatst, maar de oorspronkelijke standbenen dragen nog.','Both stepping feet are placed, but the original supporting legs still carry the weight.',d(330,202,0,f(310,160,0,.08),f(310,268,0,.92)),d(470,202,180,f(490,268,180,.92),f(490,160,180,.08))),
  k(.9,'transfer','Pas nu brengen beide dansers bovenlijf en gewicht volledig naar de nieuwe standvoet.','Only now do both dancers bring upper body and weight fully onto the new supporting foot.',d(330,178,0,f(310,160,0,.82),f(310,220,0,.18)),d(470,178,180,f(490,220,180,.18),f(490,160,180,.82))),
  k(1,'arrival','A staat links en B rechts. Als laatste sluiten de vrije benen aan, met voeten en knieën bij elkaar.','A arrives on the left and B on the right. Finally, the free legs close, with feet and knees together.',d(330,170,0,f(310,160,0,1),f(310,176,0,0)),d(470,170,180,f(490,176,180,0),f(490,160,180,1)))]},
 {id:'forward-step',nameNl:'Voorwaartse stap',nameEn:'Forward step',initiator:'a',systemNl:'parallel systeem',systemEn:'parallel system',sequenceNl:['A beweegt vanuit de as','B projecteert achterwaarts','A projecteert voorwaarts','gewicht volgt','vrije benen sluiten aan'],sequenceEn:['A moves from the axis','B projects backwards','A projects forwards','weight follows','free legs collect'],next:['side-step','cruce','backward-ocho'],keyframes:[
  k(0,'available','A draagt links en kan rechts vooruit; B draagt rechts en kan links achteruit.','A is supported on the left and can step forward with the right; B is supported on the right and can step back with the left.',walkA,walkB),
  k(.18,'proposal','A brengt eerst het lichaamscentrum naar voren, zonder de stapvoet te verplaatsen.','A first brings the body centre forward without moving the stepping foot.',d(344,250,0,f(310,232,0,1),f(310,268,0,0)),d(482,250,180,f(510,268,180,0),f(490,232,180,1))),
  k(.4,'projection','B projecteert links achterwaarts; de tenen blijven in de lichaamsrichting wijzen.','B projects the left foot backwards; the toes remain aligned with the body.',d(350,250,0,f(310,232,0,1),f(310,268,0,0)),d(492,250,180,f(548,268,180,0),f(490,232,180,1))),
  k(.62,'projection','Pas daarna projecteert A rechts voorwaarts. Beide standbenen dragen nog.','Only then does A project the right foot forwards. Both support legs still carry weight.',d(364,250,0,f(310,232,0,1),f(405,268,0,0)),d(506,250,180,f(558,268,180,0),f(490,232,180,1))),
  k(.82,'transfer','Na plaatsing dragen beiden over, afgestemd op B’s werkelijke aankomst.','After placement, both transfer, coordinated with B’s actual arrival.',d(396,250,0,f(330,232,0,.28),f(407,268,0,.72)),d(538,250,180,f(558,268,180,.72),f(500,232,180,.28))),
  k(1,'arrival','Beiden komen aan op de stapvoet en sluiten daarna het vrije been aan. Vanuit deze basishouding is een nieuwe projectie mogelijk, maar nog niet ingezet.','Both arrive on the stepping foot and then collect the free leg. A new projection is available from this neutral position but has not yet begun.',d(420,250,0,f(407,252,0,0),f(407,268,0,1)),d(560,250,180,f(548,268,180,1),f(548,252,180,0)))]},
 {id:'cruce',nameNl:'Cruce',nameEn:'Cross',initiator:'a',systemNl:'rechts verschoven → stap → ingehouden vervolg → kruising',systemEn:'offset right → step → checked continuation → cross',sequenceNl:['B staat rechts verschoven','A links vooruit, B rechts achteruit','eerste stap voltooid','A houdt volgende stap in','B kruist links voor rechts','gewicht naar links','rechts verzamelt'],sequenceEn:['B is offset to the right','A left forward, B right backward','first step completed','A checks the next step','B crosses left before right','weight moves left','right collects'],next:['forward-ocho','side-step','forward-step'],keyframes:[
  k(0,'available','B staat vanuit A gezien naar rechts verschoven; ook de torso’s zijn versprongen. B’s vrije rechtervoet staat vóór A’s rechtervoet. A draagt rechts en B links.','B is offset to A’s right, with the torsos offset as well. B’s free right foot is positioned in front of A’s right foot. A is supported on the right and B on the left.',d(330,250,0,f(310,232,0,0),f(310,268,0,1)),d(470,278,180,f(490,300,180,1),f(490,268,180,0))),
  k(.12,'proposal','A leidt een stap met links voorwaarts in vanuit een lichte torsie naar rechts. De stapvoeten blijven eerst staan; B neemt de impuls waar.','A initiates a forward step with the left from a slight twist to the right. The stepping feet initially remain still; B perceives the impulse.',d(344,252,10,f(310,232,4,0),f(310,268,4,1),3),d(480,278,184,f(490,300,180,1),f(490,268,180,0),181)),
  k(.3,'projection','B antwoordt door rechts achterwaarts te projecteren. Daarna projecteert A links voorwaarts; de oorspronkelijke standbenen dragen nog.','B responds by projecting the right backwards. A then projects the left forwards; the original supporting legs still carry the weight.',d(360,252,8,f(405,240,6,0),f(310,268,4,1),4),d(496,278,182,f(490,300,180,1),f(548,266,182,0),181)),
  k(.5,'transfer','De eerste stap wordt voltooid: A neemt gewicht op links en B op rechts. B’s linkervoet is nu vrij voor het mogelijke vervolg.','The first step is completed: A receives weight on the left and B on the right. B’s left foot is now free for a possible continuation.',d(405,252,4,f(410,240,4,1),f(310,268,4,0),2),d(548,278,180,f(490,300,180,0),f(550,266,180,1),180)),
  k(.64,'proposal','A zet geen volledige volgende voorwaartse stap. A houdt in en lost de torsie gedeeltelijk op; dit nodigt B uit om links voorlangs te kruisen.','A does not complete another forward step. A checks the movement and partly releases the twist, inviting B to cross the left foot in front.',d(414,252,0,f(410,240,0,1),f(400,268,0,0),0),d(552,276,178,f(530,300,180,0),f(550,266,178,1),179)),
  k(.78,'projection','B beweegt de vrije linkervoet vóór de rechtervoet langs en plaatst links ernaast. Rechts blijft nog volledig het standbeen.','B moves the free left foot across in front of the right and places it beside the right. The right still remains fully supporting.',d(416,252,-2,f(410,240,-1,1),f(402,268,-1,0),-1),d(548,274,178,f(538,250,178,0),f(550,266,178,1),178)),
  k(.86,'arrival','De herkenbare kruising is gevormd: links staat voor rechts, maar het gewicht bevindt zich nog op rechts.','The recognisable cross has formed: the left stands in front of the right, but the weight remains on the right.',d(418,252,-3,f(410,240,-2,1),f(404,268,-2,0),-2),d(546,274,178,f(538,250,178,0),f(550,266,178,1),178)),
  k(.94,'transfer','A heft de resterende torsie op en draait iets verder mee. Daardoor verplaatst B het gewicht van rechts naar de gekruiste linkervoet.','A releases the remaining twist and turns slightly farther with the movement. B consequently transfers weight from the right to the crossed left foot.',d(420,252,5,f(410,240,4,1),f(406,268,4,0),4),d(542,272,188,f(538,250,188,1),f(550,266,188,0),188)),
  k(1,'arrival','Na de overdracht ontspant B de gekruiste positie en verzamelt rechts naast links. Beide dansers zijn weer beschikbaar voor een nieuw voorstel.','After the transfer, B releases the crossed position and collects the right beside the left. Both dancers are available for a new proposal.',d(420,252,10,f(410,240,10,1),f(410,256,10,0),10),d(538,272,190,f(538,250,190,1),f(538,234,190,0),190))]},
 {id:'forward-ocho',nameNl:'Voorwaartse ocho',nameEn:'Forward ocho',initiator:'a',systemNl:'gekruist systeem · herhaalbare ocho-cyclus',systemEn:'crossed system · repeatable ocho cycle',sequenceNl:['A draait bovenlijf 35° links','B draait torso mee','B pivoteert gesloten','B projecteert links voorwaarts','A zet zijstap in','samen gewicht over','sluiten en 35° rechts','volgende projectie'],sequenceEn:['A turns the upper body 35° left','B follows with the torso','B pivots with feet closed','B projects left forwards','A initiates a side step','transfer together','collect and 35° right','next projection'],next:['backward-ocho','giro','side-step'],keyframes:[
  k(0,'available','Gekruist systeem: beiden dragen rechts. De voeten zijn verzameld; B’s linkerbeen is vrij.','Crossed system: both are supported on the right. The feet are collected; B’s left leg is free.',d(330,250,0,f(310,232,0,0),f(310,268,0,1)),d(470,250,180,f(490,268,180,0),f(490,232,180,1))),
  k(.12,'proposal','A begint uitsluitend met ongeveer 35° rotatie van het bovenlijf naar links. Bekken, voeten en gewicht blijven nog staan.','A begins solely with about 35° of upper-body rotation to the left. Pelvis, feet and weight remain in place.',d(330,250,-35,f(310,232,0,0),f(310,268,0,1),0),d(470,250,180,f(490,268,180,0),f(490,232,180,1),180)),
  k(.22,'pivot','B antwoordt eerst met de torso. Daarna draait het gesloten onderlichaam rond het rechterstandbeen; er is nog geen stap.','B responds first with the torso. Then the closed lower body turns around the right supporting leg; there is no step yet.',d(328,246,-35,f(310,232,-8,0),f(310,268,-8,1),-8),d(468,246,145,f(489,251,145,0),f(490,232,145,1),155)),
  k(.34,'projection','Pas na die pivot projecteert B het vrije linkerbeen voorwaarts. Rechts blijft het standbeen.','Only after that pivot does B project the free left leg forwards. The right remains the supporting leg.',d(328,236,-34,f(310,232,-12,0),f(310,268,-12,1),-12),d(462,232,145,f(414,198,145,0),f(490,232,145,1),145)),
  k(.46,'projection','A zet met links een zijstap in. Beide nieuwe voeten zijn geplaatst, maar het gewicht is nog niet overgedragen.','A initiates a side step with the left. Both new feet are placed, but weight has not yet transferred.',d(326,220,-28,f(310,178,-12,0),f(310,268,-12,1),-10),d(448,218,150,f(406,190,150,0),f(490,232,150,1),150)),
  k(.58,'transfer','A en B brengen het gewicht samen naar links. De projectie wordt zo een werkelijk uitgevoerde stap.','A and B transfer their weight to the left together. The projection thereby becomes a completed step.',d(326,190,-18,f(310,178,-10,1),f(310,250,-10,0),-10),d(414,196,160,f(406,190,160,1),f(458,220,160,0),160)),
  k(.67,'arrival','Beiden verzamelen de vrije rechtervoet. B staat stabiel op links; een volgende ocho kan beginnen of de reeks kan hier stoppen.','Both collect the free right foot. B is stable on the left; another ocho may begin or the sequence may stop here.',d(326,184,-8,f(310,178,-6,1),f(310,194,-6,0),-6),d(408,190,170,f(406,190,170,1),f(420,194,170,0),170)),
  k(.78,'proposal','A draait het bovenlijf nu ongeveer 35° naar rechts. B volgt eerst met de torso; de gesloten voeten blijven nog staan.','A now turns the upper body about 35° to the right. B first follows with the torso; the collected feet remain in place.',d(326,184,27,f(310,178,0,1),f(310,194,0,0),0),d(408,190,205,f(406,190,170,1),f(420,194,170,0),170)),
  k(.88,'pivot','Met voeten en knieën gesloten draait B beide voeten 180° door naar de andere ocho-richting, rond het linkerstandbeen. Het bekken volgt binnen de beschikbare torsieruimte.','With feet and knees collected, B turns both feet 180° into the other ocho direction, around the left supporting leg. The pelvis follows within the available torsion range.',d(328,190,30,f(310,178,12,1),f(310,194,12,0),12),d(414,196,220,f(406,190,-10,1),f(420,194,-10,0),160)),
  k(1,'projection','B gaat vloeiend over in de volgende voorwaartse projectie, nu met rechts. De bovenlijven blijven naar elkaar gericht en de achtvormige cyclus kan zich om en om herhalen.','B flows into the next forward projection, now with the right. The upper bodies remain oriented towards each other and the figure-eight cycle can repeat from side to side.',d(330,202,6,f(310,178,12,1),f(310,228,12,0),12),d(430,212,186,f(406,190,-10,1),f(474,244,210,0),160))]},
 {id:'backward-ocho',nameNl:'Achterwaartse ocho',nameEn:'Backward ocho',initiator:'a',systemNl:'gekruist systeem · herhaalbare ocho-cyclus',systemEn:'crossed system · repeatable ocho cycle',sequenceNl:['A draait bovenlijf 35° links','B projecteert links achterwaarts','A zet zijstap in','samen gewicht over','voeten en knieën sluiten','A draait 35° rechts','B: torso eerst, benen daarna','volgende projectie'],sequenceEn:['A turns the upper body 35° left','B projects left backwards','A initiates a side step','transfer together','feet and knees collect','A turns 35° right','B: torso first, legs second','next projection'],next:['forward-ocho','giro','side-step'],keyframes:[
  k(0,'available','Gekruist systeem: beiden dragen rechts, terwijl de gewone positie behouden blijft. B’s linkerbeen is vrij.','Crossed system: both are supported on the right while the normal position is retained. B’s left leg is free.',d(330,250,0,f(310,232,0,0),f(310,268,0,1)),d(470,250,180,f(490,268,180,0),f(490,232,180,1))),
  k(.12,'proposal','Initiatief A: het bovenlijf draait ongeveer 35° naar links. Bekken, voeten en gewicht blijven nog staan.','A initiates: the upper body turns about 35° to the left. Pelvis, feet and weight remain in place.',d(330,250,-35,f(310,232,0,0),f(310,268,0,1),0),d(470,250,180,f(490,268,180,0),f(490,232,180,1),180)),
  k(.24,'projection','B draait met de torso mee en projecteert als antwoord het vrije linkerbeen achterwaarts: vanuit B’s eigen lichaamsas schuin rechts-boven in dit bovenaanzicht. Rechts blijft het standbeen.','B follows with the torso and responds by projecting the free left leg backwards: from B’s own body axis, diagonally up-right in this top view. The right remains the supporting leg.',d(328,244,-35,f(310,232,-8,0),f(310,268,-8,1),-8),d(462,242,145,f(530,196,145,0),f(490,232,180,1),165)),
  k(.38,'projection','A geeft aan dat de beweging doorgaat door met links een zijstap in te zetten. De bovenlijven blijven naar elkaar gericht; beide oorspronkelijke standvoeten dragen nog.','A signals continuation by initiating a side step with the left. The upper bodies remain oriented towards each other; both original supporting feet still carry the weight.',d(340,220,-30,f(310,178,-10,0),f(310,268,-10,1),-10),d(470,222,150,f(540,190,150,0),f(490,232,170,1),160)),
  k(.52,'transfer','A en B verplaatsen samen het gewicht naar links zonder de verbinding uit te rekken. De projectie wordt pas nu een voltooide achterwaartse stap.','A and B transfer their weight to the left together without stretching the connection. Only now does the projection become a completed backward step.',d(350,190,-10,f(310,178,-10,1),f(310,250,-10,0),-10),d(500,202,160,f(540,190,160,1),f(510,218,165,0),160)),
  k(.62,'arrival','B verzamelt rechts naast links: voeten en knieën sluiten. De bovenlijven zijn weer vrijwel recht op elkaar gericht. Op deze stabiele as kan de reeks stoppen of doorgaan.','B collects the right beside the left: feet and knees close. The upper bodies are again oriented almost directly towards each other. On this stable axis the sequence can stop or continue.',d(370,190,4,f(310,178,-6,1),f(310,194,-6,0),-6),d(520,196,184,f(540,190,170,1),f(526,202,170,0),170)),
  k(.73,'proposal','A geeft de volgende ocho aan met ongeveer 35° rotatie naar rechts. B volgt eerst alleen met de torso; de gesloten voeten blijven staan en de afstand blijft behouden.','A proposes the next ocho with about 35° of rotation to the right. B first follows only with the torso; the collected feet stay put and the distance is maintained.',d(370,190,35,f(310,178,0,1),f(310,194,0,0),0),d(520,196,215,f(540,190,170,1),f(526,202,170,0),170)),
  k(.84,'pivot','Daarna draait B met voeten en knieën gesloten beide voeten 180° door naar de andere richting, rond het linkerstandbeen. Torso en bekken volgen zonder de verbinding met A los te laten.','Then B turns both feet 180° into the other direction with feet and knees collected, around the left supporting leg. Torso and pelvis follow without releasing the connection with A.',d(375,194,30,f(310,178,12,1),f(310,194,12,0),12),d(525,200,215,f(540,190,-10,1),f(526,202,-10,0),160)),
  k(1,'projection','Vanuit de draai projecteert B vloeiend het vrije rechterbeen achterwaarts, nu naar de andere lob van de acht. De bovenlijven blijven dichtbij en naar elkaar gericht.','From the turn, B smoothly projects the free right leg backwards, now into the other lobe of the figure eight. The upper bodies remain close and oriented towards each other.',d(380,198,10,f(310,178,12,1),f(310,228,12,0),12),d(530,205,190,f(540,190,-10,1),f(584,232,205,0),160))]},
 {id:'giro',nameNl:'Volledige giro',nameEn:'Complete giro',initiator:'a',systemNl:'A opent en pivoteert; B voltooit 360° rond A',systemEn:'A opens and pivots; B completes 360° around A',sequenceNl:['A opent rechtsvoor','zijstap + 90°','voorwaartse ocho','zijstap + 90°','achterwaartse ocho','A verzamelt rechts'],sequenceEn:['A opens forwards-right','side step + 90°','forward ocho','side step + 90°','backward ocho','A collects right'],next:['forward-ocho','backward-ocho','side-step'],checkpoints:[
  {at:0,nameNl:'Beginpositie',nameEn:'Starting position',supportNl:'A en B staan op links; hun rechtervoet is vrij.',supportEn:'A and B are supported on the left; their right foot is free.',techniquesNl:['A opent rechts iets naar voren','Rotatie vanuit het bovenlijf voorstellen','De straal van B’s cirkel bepalen'],techniquesEn:["A opens the right slightly forwards",'Propose rotation from the upper body',"Determine the radius of B's circle"],routesNl:['Eerste zijstap rond A','Kleinere of ruimere cirkel','Pauze vóór de giro'],routesEn:['First side step around A','Smaller or wider circle','Pause before the giro']},
  {at:.25,nameNl:'Eerste zijstap voltooid',nameEn:'First side step completed',supportNl:'B staat na 90° op rechts en blijft naar A georiënteerd.',supportEn:'After 90°, B is supported on the right and remains oriented towards A.',techniquesNl:['Pivot op rechts','Voorwaartse ocho met links','Afstand tot A moduleren'],techniquesEn:['Pivot on the right','Forward ocho with the left','Modulate distance from A'],routesNl:['Voorwaartse ocho rond A','Losse ocho of zijstap','Pauze op de nieuwe as'],routesEn:['Forward ocho around A','Independent ocho or side step','Pause on the new axis']},
  {at:.5,nameNl:'Voorwaartse ocho voltooid',nameEn:'Forward ocho completed',supportNl:'B staat op links, 180° rond A; rechts is vrij.',supportEn:'B is supported on the left, 180° around A; the right is free.',techniquesNl:['Rechts zijwaarts projecteren','Front naar A behouden','Rotatie doseren'],techniquesEn:['Project the right foot sideways','Keep the front towards A','Modulate rotation'],routesNl:['Tweede zijstap rond A','Losse zijstap','Pauze of andere richting'],routesEn:['Second side step around A','Independent side step','Pause or another direction']},
  {at:.75,nameNl:'Tweede zijstap voltooid',nameEn:'Second side step completed',supportNl:'B staat na 270° op rechts; links is vrij voor de achterwaartse ocho.',supportEn:'After 270°, B is supported on the right; the left is free for the backward ocho.',techniquesNl:['Pivot op rechts','Achterwaartse ocho met links','A’s opgebouwde torsie volgen'],techniquesEn:['Pivot on the right','Backward ocho with the left',"Follow A's accumulated torsion"],routesNl:['Achterwaartse ocho naar het einde','Losse ocho','Pauze vóór het sluiten'],routesEn:['Backward ocho to the end','Independent ocho','Pause before closing']},
  {at:1,nameNl:'Giro voltooid',nameEn:'Giro completed',supportNl:'B staat op links; A heeft rechts naast links verzameld. Beiden staan weer tegenover elkaar.',supportEn:'B is supported on the left; A has collected right beside left. Both face each other again.',techniquesNl:['B’s rechtervoet verzamelen','Verbinding ontspannen','Nieuw voorstel beginnen'],techniquesEn:["Collect B's right foot",'Relax the connection','Begin a new proposal'],routesNl:['Zijstap, ocho of wandeling','Nieuwe giro met andere straal','Pauze in basishouding'],routesEn:['Side step, ocho or walk','New giro with another radius','Pause in neutral stance']}
 ],keyframes:[
  k(0,'available','A en B dragen links. A kan rechts iets naar voren openen en daarmee een bereikbare cirkel voorstellen.','A and B are supported on the left. A can open the right slightly forwards and propose a reachable circle.',walkA,d(410,250,180,f(430,268,180,1),f(430,232,180,0))),
  k(.08,'proposal','A begint met het bovenlijf en opent de vrije rechtervoet iets naar voren. B houdt rechts nog vrij.','A begins with the upper body and opens the free right foot slightly forwards. B keeps the right free.',d(330,250,-18,f(310,232,0,1),f(352,268,-8,0),-6),d(410,250,180,f(430,268,180,1),f(430,232,180,0))),
  k(.18,'projection','A’s rechtervoet is geplaatst. B projecteert rechts zijwaarts naar de eerste kwartcirkel; links blijft exact op zijn steunpunt.','A’s right foot is placed. B projects the right sideways into the first quarter-circle; the left remains exactly on its support point.',d(330,250,-48,f(310,232,-28,.7),f(352,268,-28,.3),-28),d(390,220,135,f(430,268,155,1),f(346,180,110,0),125)),
  k(.22,'transfer','Beide voeten van B zijn geplaatst; de overdracht begint zonder dat een voet verschuift.','Both of B’s feet are placed; transfer begins without either foot sliding.',d(330,250,-72,f(310,232,-48,.62),f(352,268,-48,.38),-48),d(380,210,112,f(430,268,135,.5),f(346,180,100,.5),105)),
  k(.25,'arrival','B voltooit de zijstap op rechts, verzamelt links en is 90° rond A gedraaid.','B completes the side step on the right, collects the left and has turned 90° around A.',d(330,250,-90,f(310,232,-62,.58),f(352,268,-62,.42),-62),d(330,170,90,f(346,196,90,0),f(346,180,90,1),90)),
  k(.36,'pivot','B pivoteert op rechts voor de voorwaartse ocho. A draait verder zonder de voetposities te veranderen.','B pivots on the right for the forward ocho. A continues rotating without changing foot positions.',d(330,250,-138,f(310,232,-103,.48),f(352,268,-103,.52),-103),d(300,180,150,f(260,220,170,0),f(346,180,150,1),138)),
  k(.44,'projection','B plaatst links voorwaarts langs de cirkel; rechts blijft tijdens de projectie op hetzelfde steunpunt.','B places the left forwards along the circle; the right remains on the same support point during projection.',d(330,250,-168,f(310,232,-128,.43),f(352,268,-128,.57),-128),d(280,210,70,f(272,234,20,0),f(346,180,140,1),105)),
  k(.47,'transfer','Met beide voeten geplaatst verplaatst B het gewicht naar links.','With both feet placed, B transfers the weight to the left.',d(330,250,-176,f(310,232,-140,.41),f(352,268,-140,.59),-140),d(280,220,35,f(272,234,10,.5),f(346,180,120,.5),70)),
  k(.5,'arrival','B voltooit de voorwaartse ocho op links, halverwege de cirkel, en verzamelt rechts.','B completes the forward ocho on the left, halfway around the circle, and collects the right.',d(330,250,-180,f(310,232,-148,.4),f(352,268,-148,.6),-148),d(250,250,0,f(272,234,0,1),f(272,266,0,0),0)),
  k(.64,'projection','B projecteert rechts zijwaarts naar de derde kwartcirkel; de linkerstandvoet blijft staan.','B projects the right sideways into the third quarter-circle; the left support foot remains fixed.',d(330,250,-238,f(310,232,-198,.36),f(352,268,-198,.64),-198),d(280,300,-45,f(272,234,-20,1),f(346,314,-70,0),-45)),
  k(.71,'transfer','Na plaatsing van rechts vindt de overdracht plaats zonder voetverschuiving.','After placement of the right, transfer occurs without foot displacement.',d(330,250,-256,f(310,232,-218,.34),f(352,268,-218,.66),-218),d(300,320,-70,f(272,234,-35,.5),f(346,314,-80,.5),-65)),
  k(.75,'arrival','B voltooit de tweede zijstap op rechts na 270° en verzamelt links. Bij A is de torsie nu het grootst.','B completes the second side step on the right after 270° and collects the left. A’s torsion is now greatest.',d(330,250,-270,f(310,232,-230,.32),f(352,268,-230,.68),-230),d(330,330,-90,f(314,314,-90,0),f(346,314,-90,1),-90)),
  k(.84,'pivot','B pivoteert op rechts voor de achterwaartse ocho. A behoudt de voetposities en leidt vanuit de opgebouwde torsie.','B pivots on the right for the backward ocho. A retains the foot positions and leads from the accumulated torsion.',d(330,250,-310,f(310,232,-265,.28),f(352,268,-265,.72),-265),d(370,320,-155,f(410,280,-175,0),f(346,314,-140,1),-135)),
  k(.91,'projection','B plaatst links achterwaarts in de eindpositie; rechts blijft tijdens de projectie op zijn steunpunt. A begint rechts te verzamelen.','B places the left backwards in the end position; the right remains on its support point during projection. A begins collecting the right.',d(330,250,-340,f(310,232,-310,.65),f(334,254,-310,.35),-310),d(390,290,-195,f(430,268,-190,0),f(346,314,-150,1),-170)),
  k(.95,'transfer','Met beide voeten geplaatst draagt B over naar links. A heft tegelijk de resterende spanning op.','With both feet placed, B transfers to the left. A simultaneously releases the remaining tension.',d(330,250,-352,f(310,232,-340,.85),f(320,250,-340,.15),-340),d(400,270,-185,f(430,268,-185,.5),f(346,314,-165,.5),-180)),
  k(1,'arrival','B voltooit 360° en staat weer tegenover A. A heeft rechts naast links verzameld; B verzamelt eveneens de vrije rechtervoet.','B completes 360° and faces A again. A has collected right beside left; B also collects the free right foot.',d(330,250,-360,f(310,232,-360,1),f(310,248,-360,0),-360),d(410,250,-180,f(430,268,-180,1),f(430,252,-180,0),-180))]}
]

const lerp=(a:number,b:number,t:number)=>a+(b-a)*t
const angleLerp=(a:number,b:number,t:number)=>a+(((b-a+540)%360)-180)*t
const pointLerp=(a:Point,b:Point,t:number):Point=>({x:lerp(a.x,b.x,t),y:lerp(a.y,b.y,t)})
const distance=(a:Point,b:Point)=>Math.hypot(a.x-b.x,a.y-b.y)
const signedAngleDelta=(a:number,b:number)=>((a-b+540)%360)-180
const footLerp=(a:FootState,b:FootState,t:number):FootState=>{
 const travel=distance(a,b),swing=Math.max(a.clearance??0,b.clearance??0,travel>4&&Math.min(a.load,b.load)<.2?Math.sin(Math.PI*t)*9:0)
 return{...pointLerp(a,b,t),angle:angleLerp(a.angle,b.angle,t),load:lerp(a.load,b.load,t),clearance:swing}
}
const dancerLerp=(a:DancerState,b:DancerState,t:number):DancerState=>({torso:pointLerp(a.torso,b.torso,t),angle:angleLerp(a.angle,b.angle,t),pelvisAngle:angleLerp(a.pelvisAngle,b.pelvisAngle,t),left:footLerp(a.left,b.left,t),right:footLerp(a.right,b.right,t)})
const hipFor=(x:DancerState,side:'left'|'right'):Point=>{const r=x.pelvisAngle*Math.PI/180,o=side==='left'?-BODY_LIMITS.hipHalfWidth:BODY_LIMITS.hipHalfWidth;return{x:x.torso.x-Math.sin(r)*o,y:x.torso.y+Math.cos(r)*o}}
const clampFoot=(foot:FootState,hip:Point):FootState=>{const reach=distance(foot,hip),max=BODY_LIMITS.thighLength+BODY_LIMITS.shinLength-2;if(reach<=max)return{...foot,load:Math.max(0,Math.min(1,foot.load)),clearance:Math.max(0,foot.clearance??0)};const scale=max/reach;return{...foot,x:hip.x+(foot.x-hip.x)*scale,y:hip.y+(foot.y-hip.y)*scale,load:Math.max(0,Math.min(1,foot.load)),clearance:Math.max(0,foot.clearance??0)}}
const constrainDancer=(source:DancerState):DancerState=>{const twist=signedAngleDelta(source.angle,source.pelvisAngle),pelvisAngle=Math.abs(twist)>BODY_LIMITS.maxTorsoPelvisTwist?source.angle-Math.sign(twist)*BODY_LIMITS.maxTorsoPelvisTwist:source.pelvisAngle;const base={...source,pelvisAngle};let left=clampFoot(base.left,hipFor(base,'left')),right=clampFoot(base.right,hipFor(base,'right'));const total=left.load+right.load||1;left={...left,load:left.load/total};right={...right,load:right.load/total};const gap=distance(left,right),canOverlap=Math.max(left.clearance??0,right.clearance??0)>0;if(gap<BODY_LIMITS.minFootClearance&&!canOverlap){const free=left.load<=right.load?'left':'right',fixed=free==='left'?right:left,move=free==='left'?left:right,dx=move.x-fixed.x,dy=move.y-fixed.y,len=Math.hypot(dx,dy)||1,adjusted={...move,x:fixed.x+dx/len*BODY_LIMITS.minFootClearance,y:fixed.y+dy/len*BODY_LIMITS.minFootClearance};if(free==='left')left=adjusted;else right=adjusted}return{...base,left,right}}
const constrainFrame=(frame:TangoFrame):TangoFrame=>({...frame,a:constrainDancer(frame.a),b:constrainDancer(frame.b)})
export function rawFrameAt(movement:Movement,progress:number):TangoFrame{const p=Math.max(0,Math.min(1,progress)),found=movement.keyframes.findIndex(x=>x.at>=p);if(found===0)return{...movement.keyframes[0],progress:p};const hi=found<0?movement.keyframes.length-1:Math.max(1,found),from=movement.keyframes[hi-1],to=movement.keyframes[hi],local=(p-from.at)/Math.max(.0001,to.at-from.at),nearer=local<.5?from:to;return{a:dancerLerp(from.a,to.a,local),b:dancerLerp(from.b,to.b,local),contacts:from.contacts.slice(0,Math.min(from.contacts.length,to.contacts.length)).map((c,i)=>({type:c.type,a:pointLerp(c.a,to.contacts[i].a,local),b:pointLerp(c.b,to.contacts[i].b,local),active:lerp(c.active,to.contacts[i].active,local)})),phase:nearer.phase,noteNl:nearer.noteNl,noteEn:nearer.noteEn,progress:p}}
export function frameAt(movement:Movement,progress:number):TangoFrame{return constrainFrame(rawFrameAt(movement,progress))}
export function legJoints(x:DancerState,side:'left'|'right'):LegJoints{const hip=hipFor(x,side),ankle=x[side],span=distance(hip,ankle),reachable=span<=BODY_LIMITS.thighLength+BODY_LIMITS.shinLength;const safe=Math.max(1,Math.min(span,BODY_LIMITS.thighLength+BODY_LIMITS.shinLength-1)),mid={x:(hip.x+ankle.x)/2,y:(hip.y+ankle.y)/2},height=Math.sqrt(Math.max(0,BODY_LIMITS.thighLength**2-(safe/2)**2)),nx=-(ankle.y-hip.y)/safe,ny=(ankle.x-hip.x)/safe,bend=side==='left'?-1:1;return{hip,knee:{x:mid.x+nx*height*bend,y:mid.y+ny*height*bend},ankle:{x:ankle.x,y:ankle.y},reachable}}
export function assessBiomechanics(frame:TangoFrame):BiomechanicalCheck[]{const dancers=[frame.a,frame.b],feet=dancers.flatMap(x=>[x.left,x.right]);return[
 {id:'reach',ok:dancers.every(x=>(['left','right'] as const).every(s=>legJoints(x,s).reachable)),labelNl:'Beide benen binnen anatomisch bereik',labelEn:'Both legs within anatomical reach'},
 {id:'torsion',ok:dancers.every(x=>Math.abs(signedAngleDelta(x.angle,x.pelvisAngle))<=BODY_LIMITS.maxTorsoPelvisTwist+.1),labelNl:'Torsie bovenlijf–bekken begrensd',labelEn:'Upper-body–pelvis torsion constrained'},
 {id:'load',ok:dancers.every(x=>Math.abs(x.left.load+x.right.load-1)<.01),labelNl:'Voetbelasting sluit op 100%',labelEn:'Foot loads sum to 100%'},
 {id:'clearance',ok:dancers.every(x=>distance(x.left,x.right)>=BODY_LIMITS.minFootClearance||Math.max(x.left.clearance??0,x.right.clearance??0)>0),labelNl:'Voeten passeren zonder doorsnijding',labelEn:'Feet pass without intersection'},
 {id:'balance',ok:dancers.every(x=>Math.min(...(['left','right'] as const).filter(s=>x[s].load>.2).map(s=>distance(x.torso,x[s])))<=BODY_LIMITS.maxSupportDistance),labelNl:'Bovenlijf blijft bereikbaar boven steunbasis',labelEn:'Upper body remains reachable over support base'}]}
export function assessMovementAt(movement:Movement,progress:number):BiomechanicalCheck[]{const frame=rawFrameAt(movement,progress),epsilon=.0025,before=rawFrameAt(movement,Math.max(0,progress-epsilon)),after=rawFrameAt(movement,Math.min(1,progress+epsilon)),supportStable=(['a','b'] as const).every(id=>(['left','right'] as const).every(side=>before[id][side].load<=.85||after[id][side].load<=.85||distance(before[id][side],after[id][side])<=1.8)),towards=(from:DancerState,to:DancerState)=>direction(from.torso,to.torso),facingA=Math.abs(signedAngleDelta(frame.a.angle,towards(frame.a,frame.b))),facingB=Math.abs(signedAngleDelta(frame.b.angle,towards(frame.b,frame.a))),separation=distance(frame.a.torso,frame.b.torso),connection=separation<=PARTNER_LIMITS.maxTorsoSeparation&&facingA<=PARTNER_LIMITS.maxFacingError&&facingB<=PARTNER_LIMITS.maxFacingError,endAligned=progress<.995||(facingA<=20&&facingB<=20),backwardComponent=(from:FootState,to:FootState,bodyAngle:number)=>{const radians=(bodyAngle+180)*Math.PI/180;return(to.x-from.x)*Math.cos(radians)+(to.y-from.y)*Math.sin(radians)},directionValid=movement.id!=='backward-ocho'||(progress>=.12&&progress<=.62?backwardComponent(rawFrameAt(movement,0).b.left,frame.b.left,frame.b.angle)>=-.5:progress>=.84?backwardComponent(rawFrameAt(movement,.84).b.right,frame.b.right,frame.b.angle)>=-.5:true);return[...assessBiomechanics(frame),{id:'support',ok:supportStable,labelNl:'Belaste standvoeten schuiven niet',labelEn:'Loaded support feet do not slide'},{id:'direction',ok:directionValid,labelNl:'Ocho-projectie ligt achter de eigen lichaamsas',labelEn:'Ocho projection lies behind the dancer’s own body axis'},{id:'connection',ok:connection,labelNl:'Bovenlijven blijven nabij en naar elkaar gericht',labelEn:'Upper bodies remain close and mutually oriented'},{id:'orientation',ok:endAligned,labelNl:'Eindhouding is wederzijds georiënteerd',labelEn:'Final stance is mutually oriented'}]}
export const centreOfMass=(x:DancerState):Point=>({x:x.torso.x*.78+x.left.x*.11+x.right.x*.11,y:x.torso.y*.78+x.left.y*.11+x.right.y*.11})
export const sharedCentre=(x:TangoFrame):Point=>{const a=centreOfMass(x.a),b=centreOfMass(x.b);return{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}

const direction=(from:Point,to:Point)=>Math.atan2(to.y-from.y,to.x-from.x)*180/Math.PI
const bodyPoint=(x:DancerState,forward:number,side:number):Point=>{
  const radians=x.angle*Math.PI/180
  return{x:x.torso.x+Math.cos(radians)*forward-Math.sin(radians)*side,y:x.torso.y+Math.sin(radians)*forward+Math.cos(radians)*side}
}
const moveDancer=(x:DancerState,dx:number,dy:number,shoulderAngle:number):DancerState=>({
  torso:{x:x.torso.x+dx,y:x.torso.y+dy},angle:shoulderAngle,pelvisAngle:x.pelvisAngle,
  left:{...x.left,x:x.left.x+dx,y:x.left.y+dy},right:{...x.right,x:x.right.x+dx,y:x.right.y+dy}
})

/** Presentation transform: the authored footwork remains unchanged while distance,
 * upper-body orientation and contact adapt to the selected abrazo. */
export function withEmbrace(frame:TangoFrame,embrace:Embrace,movementId:MovementId):TangoFrame{
  const midpoint={x:(frame.a.torso.x+frame.b.torso.x)/2,y:(frame.a.torso.y+frame.b.torso.y)/2}
  const distanceFactor={open:1,'half-open':.76,closed:.58}[embrace]
  const shoulderFollow={open:.24,'half-open':.68,closed:.94}[embrace]
  const adapt=(x:DancerState,other:DancerState,id:DancerId)=>{
    const baseTarget={x:midpoint.x+(x.torso.x-midpoint.x)*distanceFactor,y:midpoint.y+(x.torso.y-midpoint.y)*distanceFactor}
    const facing=direction(baseTarget,other.torso)
    // In half-open embrace both dancers shift slightly towards their own left.
    // This brings their right torso sides together while preserving space left.
    const lateral=embrace==='half-open'?20:0
    const radians=facing*Math.PI/180
    const target={x:baseTarget.x+Math.sin(radians)*lateral,y:baseTarget.y-Math.cos(radians)*lateral}
    const ochoExtra=(movementId==='forward-ocho'||movementId==='backward-ocho')&&embrace==='open'?.08:0
    // In a half-open embrace both chests turn slightly in the same stage
    // direction: their right side meets while the left side remains open.
    const halfOpenOffset=embrace==='half-open'?(id==='a'?10:-10):0
    return moveDancer(x,target.x-x.torso.x,target.y-x.torso.y,angleLerp(x.angle,facing,Math.min(1,shoulderFollow+ochoExtra))+halfOpenOffset)
  }
  const a=adapt(frame.a,frame.b,'a'),b=adapt(frame.b,frame.a,'b')
  const contacts:Contact[]=embrace==='open'?[{
    type:'hand',a:bodyPoint(a,16,-48),b:bodyPoint(b,16,48),active:1
  },{
    type:'arm',a:bodyPoint(a,12,34),b:bodyPoint(b,8,-30),active:.9
  }]:embrace==='half-open'?[{
    type:'hand',a:bodyPoint(a,12,-44),b:bodyPoint(b,12,44),active:1
  },{
    type:'arm',a:bodyPoint(a,-2,34),b:bodyPoint(b,-12,-34),active:.95
  },{
    type:'torso',a:bodyPoint(a,38,20),b:bodyPoint(b,38,20),active:.72
  }]:[{
    type:'hand',a:bodyPoint(a,8,-40),b:bodyPoint(b,8,40),active:1
  },{
    type:'arm',a:bodyPoint(a,-8,34),b:bodyPoint(b,-8,-34),active:1
  },{
    type:'torso',a:bodyPoint(a,38,0),b:bodyPoint(b,38,0),active:1
  }]
  return{...frame,a,b,contacts}
}
